Repository WPMedia/arc-themes-blocks, pull requests merged in 2020-10, with the labels that each got.

#473 Remove deprecated docs
  News Theme Development.md
Labels: client-docs

#500 PEN-1395: Incorporate Google Ad work from TVNZ into an Arc Block
  blocks/ads-block/CHANGELOG.md
  blocks/ads-block/README.md
  blocks/ads-block/features/ads/_children/ArcAdminAd/index.jsx
  blocks/ads-block/features/ads/_children/ArcAdminAd/index.scss
  blocks/ads-block/features/ads/_children/ArcAdminAd/index.test.jsx
  blocks/ads-block/features/ads/_children/ArcAdsInstance/index.js
  blocks/ads-block/features/ads/_children/ArcAdsInstance/index.test.js
  blocks/ads-block/features/ads/ad-helper.js
  blocks/ads-block/features/ads/ad-helper.test.js
  blocks/ads-block/features/ads/ad-mapping.js
  blocks/ads-block/features/ads/ads.scss
  blocks/ads-block/features/ads/default.jsx
  blocks/ads-block/features/ads/default.test.jsx
  blocks/ads-block/index.js
  blocks/ads-block/jest.config.js
  blocks/ads-block/package-lock.json
  blocks/ads-block/package.json
  package-lock.json
  package.json
Labels: advertisement

#513 Revert "Use promo-headline branch changes without breaking tests"
  blocks/medium-promo-block/features/medium-promo/default.jsx
  blocks/medium-promo-block/features/medium-promo/default.scss
  blocks/medium-promo-block/features/medium-promo/default.test.jsx
  blocks/shared-styles/scss/_extra-large-promo.scss
  blocks/shared-styles/scss/_small-promo.scss
  blocks/small-promo-block/features/small-promo/default.jsx
  blocks/top-table-list-block/features/top-table-list/_children/horizontal-overline-image-story-item.jsx
  blocks/top-table-list-block/features/top-table-list/_children/horizontal-overline-image-story-item.test.jsx
  blocks/top-table-list-block/features/top-table-list/_children/item-title-with-right-image.jsx
  blocks/top-table-list-block/features/top-table-list/_children/item-title-with-right-image.test.jsx
  blocks/top-table-list-block/features/top-table-list/_children/medium-list-item.jsx
  blocks/top-table-list-block/features/top-table-list/_children/medium-list-item.test.jsx
  blocks/top-table-list-block/features/top-table-list/_children/vertical-overline-image-story-item.jsx
  blocks/top-table-list-block/features/top-table-list/_children/vertical-overline-image-story-item.test.jsx
  blocks/top-table-list-block/features/top-table-list/default.jsx
  blocks/top-table-list-block/features/top-table-list/default.scss
  package.json
Labels: do-not-merge
