Repository WPMedia/arc-themes-blocks, pull requests merged in 2022-03, with the labels that each got.

#1286 Tmedia 601 show caption video options
  blocks/article-body-block/chains/article-body/_articlebody.scss
  blocks/article-body-block/chains/article-body/default.jsx
  blocks/article-body-block/chains/article-body/default.test.jsx
  blocks/lead-art-block/features/leadart/default.jsx
  blocks/lead-art-block/features/leadart/default.test.jsx
  blocks/lead-art-block/features/leadart/leadart.scss
  blocks/lead-art-block/index.story.jsx
  blocks/video-player-block/features/video-player/default.jsx
Labels: question, ready to merge

#1287 TBRANDS-26: Single Column Layout
  blocks/single-column-layout-block/README.md
  blocks/single-column-layout-block/index.js
  blocks/single-column-layout-block/jest.config.js
  blocks/single-column-layout-block/layouts/.npmignore
  blocks/single-column-layout-block/layouts/single-column-regular/default.jsx
  blocks/single-column-layout-block/layouts/single-column-regular/default.test.jsx
  blocks/single-column-layout-block/layouts/single-column-regular/index.story.jsx
  blocks/single-column-layout-block/layouts/single-column-regular/styles.scss
  blocks/single-column-layout-block/package.json
  package-lock.json
  package.json
Labels: ready for review

#1289 Update Feature generators for enhanced styling architecture
  .storybook/.babelrc
  _templates/chain/new/faux-entry.ejs.t
  _templates/chain/new/package.ejs.t
  _templates/chain/new/scss-entry.ejs.t
  _templates/feature/feature/default-entry.ejs.t
  _templates/feature/feature/default-test.ejs.t
  _templates/feature/feature/storybook-main.ejs.t
  _templates/feature/new/default-entry.ejs.t
  _templates/feature/new/default-test.ejs.t
  _templates/feature/new/faux-entry.ejs.t
  _templates/feature/new/package.ejs.t
  _templates/feature/new/readme.ejs.t
  _templates/feature/new/scss-entry.ejs.t
  _templates/feature/new/storybook.ejs.t
  babel.config.js
  package-lock.json
  package.json
Labels: ready for review

#1284 Small Improvement: Prevent direct state management which could cause issues
  blocks/search-results-list-block/features/search-results-list/_children/custom-content.jsx
  blocks/search-results-list-block/features/search-results-list/_children/global-content.jsx
Labels: small-improvement

#1293 Storybook updates for components loading
  .storybook/main.js
  .storybook/manager.js
Labels: ready to merge

#1299 TMEDIA-601 - Blank Strings fix
  blocks/video-player-block/features/video-player/default.jsx
  package-lock.json
Labels: ready for review

#1297 TMEDIA 708: Use subs subtitle rather than duplicating title
  blocks/subscriptions-block/components/useOffer.test.jsx
  blocks/subscriptions-block/features/offer/default.jsx
  blocks/subscriptions-block/features/offer/default.test.jsx
Labels: ready for review
