Repository WPMedia/arc-themes-blocks, pull requests merged in 2022-07, with the labels that each got.

#1394 Tmedia 751 card list refactor v2
  .storybook/mock-content/simpleList.js
  .storybook/themes/news.scss
  blocks/card-list-block/README.md
  blocks/card-list-block/_index.scss
  blocks/card-list-block/features/card-list/card-list.scss
  blocks/card-list-block/features/card-list/default.jsx
  blocks/card-list-block/features/card-list/default.test.jsx
  blocks/card-list-block/features/card-list/mock-data.js
  blocks/card-list-block/index.js
  blocks/card-list-block/index.story.jsx
  blocks/card-list-block/package.json
Labels: ready to merge

#1402 chore: Copy feature pack styles to blocks. Update colors
  .storybook/themes/news.scss
Labels: ready to merge

#1395 Tmedia-745: large manual promo block refactor
  .storybook/themes/news.scss
  blocks/large-manual-promo-block/README.md
  blocks/large-manual-promo-block/_index.scss
  blocks/large-manual-promo-block/features/large-manual-promo/default.jsx
  blocks/large-manual-promo-block/features/large-manual-promo/default.test.jsx
  blocks/large-manual-promo-block/index.js
  blocks/large-manual-promo-block/index.story.jsx
  blocks/large-manual-promo-block/package.json
Labels: ready to merge

#1407 Tmedia 746 medium manual modifiers
  .storybook/themes/news.scss
  blocks/medium-manual-promo-block/_index.scss
  blocks/medium-manual-promo-block/features/medium-manual-promo/default.jsx
  blocks/medium-manual-promo-block/features/medium-manual-promo/default.test.jsx
Labels: ready for review, feedback-pr

#1413 docs: Add large promo label examples for video and gallery icon
  blocks/large-promo-block/index.story.jsx
Labels: ready to merge

#1415 tmedia 741: docs: Add videoPlayInPlace example along with an explanation
  blocks/large-promo-block/index.story.jsx
Labels: ready to merge

#1416 TMEIA-916 generator update
  _templates/content-source/content-source/default-entry.ejs.t
  _templates/content-source/content-source/default-test.ejs.t
  _templates/content-source/new/default-entry.ejs.t
  _templates/content-source/new/default-test.ejs.t
  _templates/content-source/new/package.ejs.t
  _templates/feature/content-source/default-entry.ejs.t
  _templates/feature/content-source/default-test.ejs.t
Labels: ready to merge

#1417 TMEDIA-746 - Adjust spacing to inline with designs
  .storybook/themes/news.scss
Labels: ready for design qa

#1424 Convert tests to use RTL
  blocks/medium-manual-promo-block/features/medium-manual-promo/default.test.jsx
Labels: ready for review

#1421 Updates to tokens to address component regressions
  .storybook/themes/news.scss
Labels: ready to merge

#1426 chore: Remove packages from unused block
  blocks/a11y-testing-block/package-lock.json
  blocks/a11y-testing-block/package.json
Labels: ready to merge

#1412 Tmedia 743 small promo block
  .storybook/themes/news.scss
  blocks/shared-styles/_children/promo-helpers/small/__snapshots__/container.test.jsx.snap
  blocks/shared-styles/_children/promo-helpers/small/container.jsx
  blocks/shared-styles/_children/promo-helpers/small/container.test.jsx
  blocks/shared-styles/_children/promo-helpers/small/styles.jsx
  blocks/shared-styles/_children/promo-helpers/small/styles.test.jsx
  blocks/shared-styles/_children/promos/small/index.jsx
  blocks/shared-styles/_children/promos/small/index.test.jsx
  blocks/shared-styles/_children/promos/small/mock-data.js
  blocks/shared-styles/index.js
  blocks/small-promo-block/README.md
  blocks/small-promo-block/_index.scss
  blocks/small-promo-block/features/small-promo/default.jsx
  blocks/small-promo-block/features/small-promo/default.test.jsx
  blocks/small-promo-block/index.js
  blocks/small-promo-block/index.story.jsx
  blocks/small-promo-block/package.json
  package-lock.json
Labels: ready for design qa

#1432 TBRANDS-94 - Commerce Product Content Source
  blocks/commerce-product-content-source-block/README.md
  blocks/commerce-product-content-source-block/jest.config.js
  blocks/commerce-product-content-source-block/package.json
  blocks/commerce-product-content-source-block/sources/.npmignore
  blocks/commerce-product-content-source-block/sources/commerce-product.js
  blocks/commerce-product-content-source-block/sources/commerce-product.test.js
  blocks/commerce-product-content-source-block/sources/mock-data.js
  package.json
Labels: ready to merge

#1433 TBRANDS-94 - Remove mock from ignore for now
  blocks/commerce-product-content-source-block/sources/.npmignore
Labels: ready to merge

#1427 fixed no content error
  blocks/large-manual-promo-block/features/large-manual-promo/default.jsx
Labels: ready for review

#1435 TMEDIA-743 QA Issue - Fix for custom image to render
  blocks/small-promo-block/features/small-promo/default.jsx
Labels: ready to merge

#1436 TBRANDS-96 - Add Product Information block
  .storybook/themes/commerce.scss
  blocks/product-information-block/README.md
  blocks/product-information-block/_index.scss
  blocks/product-information-block/features/product-information/default.jsx
  blocks/product-information-block/features/product-information/default.test.jsx
  blocks/product-information-block/index.story.jsx
  blocks/product-information-block/jest.config.js
  blocks/product-information-block/package.json
  package.json
Labels: ready to merge

#1438 Docs themes setup feedback
  PACKAGE_CS_README_TEMPLATE.md
  PACKAGE_FEATURE_README_TEMPLATE.md
  README.md
  Theme Development.md
  stories/aaaIntro.stories.mdx
  themes-git-flow.png
Labels: ready for review

#1441 Get latest Arc Themes Components Package
  .storybook/themes/news.scss
  package-lock.json
  package.json
Labels: ready for review

#1440 TBRANDS-96 - Update CSS and Heading
  .storybook/themes/commerce.scss
  blocks/product-information-block/features/product-information/default.jsx
Labels: ready to merge

#1418 TMEDIA-740: Convert Extra Large Promo Block
  .storybook/themes/news.scss
  blocks/extra-large-promo-block/README.md
  blocks/extra-large-promo-block/_index.scss
  blocks/extra-large-promo-block/features/extra-large-promo/default.jsx
  blocks/extra-large-promo-block/features/extra-large-promo/default.test.jsx
  blocks/extra-large-promo-block/features/extra-large-promo/mock-data-sponsored.js
  blocks/extra-large-promo-block/features/extra-large-promo/mock-data.js
  blocks/extra-large-promo-block/index.js
  blocks/extra-large-promo-block/package-lock.json
  blocks/extra-large-promo-block/package.json
  blocks/shared-styles/_children/headings/heading/index.jsx
  blocks/shared-styles/_children/headings/section/index.jsx
  blocks/shared-styles/_children/promos/extra-large/index.jsx
  blocks/shared-styles/_children/promos/extra-large/index.test.jsx
  blocks/shared-styles/_children/promos/extra-large/mock-data-video.js
  blocks/shared-styles/index.js
  blocks/top-table-list-block/features/top-table-list/default.jsx
  package.json
Labels: ready to merge

#1446 Small improvement: fix generator description typo
  _templates/chain/new/readme.ejs.t
  _templates/feature/new/readme.ejs.t
  blocks/category-carousel-block/README.md
Labels: ready to merge

#1442 TMEDIA-741 - Remove the extra grid
  .storybook/themes/news.scss
  blocks/large-manual-promo-block/features/large-manual-promo/default.jsx
  blocks/large-manual-promo-block/features/large-manual-promo/default.test.jsx
  blocks/large-promo-block/features/large-promo/default.jsx
  package-lock.json
Labels: ready for review, feedback-pr

#1449 docs: Add link to confluence notes based on dev feedback
  README.md
Labels: small-improvement

#1450 Make commerce tokens same as feature pack
  .storybook/themes/commerce.scss
Labels: ready to merge

#1452 TBRANDS-81 -- Update list and sales price display logic
  .storybook/mock-content/algoliaProduct.js
  blocks/product-assortment-carousel-block/features/product-assortment-carousel/default.jsx
  blocks/product-assortment-carousel-block/features/product-assortment-carousel/default.test.jsx
Labels: ready to merge

#1453 Chromatic - Article Body embed false positives
  blocks/article-body-block/index.story.jsx
Labels: ready to merge

#1437 TMEDIA-755 simple list block
  .storybook/themes/news.scss
  blocks/simple-list-block/_index.scss
  blocks/simple-list-block/features/simple-list/_children/story-item.jsx
  blocks/simple-list-block/features/simple-list/_children/story-item.test.jsx
  blocks/simple-list-block/features/simple-list/default.jsx
  blocks/simple-list-block/features/simple-list/default.test.jsx
  blocks/simple-list-block/features/simple-list/simple-list.scss
  blocks/simple-list-block/package.json
Labels: ready for design qa
