Repository WPMedia/arc-themes-blocks, pull requests merged in 2022-12, with the labels that each got.

#1560 THEMES-733
  .storybook/mock-content/simpleList.js
  blocks/card-list-block/features/card-list/default.jsx
  blocks/card-list-block/features/card-list/default.test.jsx
  blocks/card-list-block/features/card-list/mock-data.js
  jest/mocks/properties.js
Labels: ready for review

#1564 THEMES-734: Numbered List Block | Resizer V2
  blocks/numbered-list-block/features/numbered-list/default.jsx
  blocks/numbered-list-block/features/numbered-list/mock-data.js
Labels: ready to merge

#1561 THEMES-735 - Simple List block resizer v2 updates
  blocks/simple-list-block/features/simple-list/_children/story-item.jsx
  blocks/simple-list-block/features/simple-list/_children/story-item.test.jsx
  blocks/simple-list-block/features/simple-list/default.jsx
  blocks/simple-list-block/features/simple-list/default.test.jsx
Labels: ready to merge

#1566 THEMES-705 - Date block v2
  .storybook/alias/context.js
  .storybook/themes/news.scss
  blocks/date-block/README.md
  blocks/date-block/_index.scss
  blocks/date-block/features/date/date.scss
  blocks/date-block/features/date/default.jsx
  blocks/date-block/features/date/default.test.jsx
  blocks/date-block/index.story.jsx
  blocks/date-block/package.json
Labels: ready to merge

#1563 THEMES-714 - Convert section title block to v2 and update tests to RTL
  .storybook/themes/news.scss
  blocks/section-title-block/README.md
  blocks/section-title-block/_index.scss
  blocks/section-title-block/features/section-title/_children/custom-content.jsx
  blocks/section-title-block/features/section-title/_children/custom-content.test.jsx
  blocks/section-title-block/features/section-title/_children/global-content.jsx
  blocks/section-title-block/features/section-title/_children/global-content.test.jsx
  blocks/section-title-block/features/section-title/_children/mock-data.js
  blocks/section-title-block/features/section-title/_children/section-title.jsx
  blocks/section-title-block/features/section-title/_children/section-title.scss
  blocks/section-title-block/features/section-title/_children/section-title.test.jsx
  blocks/section-title-block/features/section-title/default.jsx
  blocks/section-title-block/features/section-title/default.test.jsx
  blocks/section-title-block/features/section-title/mock-data.js
  blocks/section-title-block/index.js
  blocks/section-title-block/index.story.jsx
  blocks/section-title-block/package.json
Labels: ready to merge

#1537 coverted results-list block into V2
  .storybook/mock-content/resultsList.js
  .storybook/themes/news.scss
  blocks/results-list-block/README.md
  blocks/results-list-block/_index.scss
  blocks/results-list-block/features/results-list/default.jsx
  blocks/results-list-block/features/results-list/default.test.jsx
  blocks/results-list-block/features/results-list/results/index.jsx
  blocks/results-list-block/features/results-list/results/index.test.jsx
  blocks/results-list-block/features/results-list/results/result-item.jsx
  blocks/results-list-block/features/results-list/results/result-item.test.jsx
  blocks/results-list-block/index.js
  blocks/results-list-block/index.story.jsx
  blocks/results-list-block/package.json
  blocks/shared-styles/scss/_results-list.scss
  package-lock.json
Labels: additional review

#1569 Update defaults to use supported format
  .storybook/alias/properties.js
  blocks/card-list-block/features/card-list/default.jsx
  blocks/date-block/features/date/default.jsx
  blocks/date-block/features/date/default.test.jsx
  blocks/extra-large-promo-block/features/extra-large-promo/default.jsx
  blocks/large-promo-block/features/large-promo/default.jsx
  blocks/masthead-block/features/masthead-block/default.jsx
  blocks/medium-promo-block/features/medium-promo/default.jsx
  blocks/shared-styles/_children/promo-date/index.jsx
  blocks/shared-styles/_children/promo-date/index.test.jsx
  blocks/top-table-list-block/features/top-table-list/_children/extra-large.jsx
  blocks/top-table-list-block/features/top-table-list/_children/large.jsx
  blocks/top-table-list-block/features/top-table-list/_children/medium.jsx
Labels: ready to merge

#1573 THEMES-718 added translations
  blocks/results-list-block/package.json
Labels: ready for review

#1577 Themes 718 Updated readme to get package.json file be deployed
  blocks/results-list-block/README.md
Labels: ready for review

#1574 THEMES-796 - Create storybook for test case
  blocks/medium-manual-promo-block/index.story.jsx
  blocks/medium-promo-block/index.story.jsx
Labels: ready to merge

#1575 THEMES-796 - Medium Promo's stacked
  .storybook/themes/news.scss
  blocks/medium-promo-block/features/medium-promo/default.jsx
Labels: ready to merge

#1578 THEMES-751 - Add divider block
  .storybook/themes/news.scss
  blocks/divider-block/README.md
  blocks/divider-block/_index.scss
  blocks/divider-block/features/divider/default.jsx
  blocks/divider-block/features/divider/default.test.jsx
  blocks/divider-block/index.story.jsx
  blocks/divider-block/jest.config.js
  blocks/divider-block/package.json
  package-lock.json
  package.json
Labels: ready for design qa

#1580 THEMES-720 - Convert ad taboola block to v2
  blocks/ad-taboola-block/README.md
  blocks/ad-taboola-block/features/ad-taboola/default.jsx
  blocks/ad-taboola-block/features/ad-taboola/default.test.jsx
  blocks/ad-taboola-block/index.js
  blocks/ad-taboola-block/package.json
Labels: ready to merge

#1581 THEMES-836: Quilted Image Block - QA fix
  blocks/quilted-image-block/features/quilted-image/default.jsx
  blocks/quilted-image-block/index.story.jsx
Labels: ready to merge

#1556 THEMES-722: Search Results List
  .storybook/themes/news.scss
  blocks/search-results-list-block/_index.scss
  blocks/search-results-list-block/features/search-results-list/_children/custom-content.jsx
  blocks/search-results-list-block/features/search-results-list/_children/custom-content.test.jsx
  blocks/search-results-list-block/features/search-results-list/_children/global-content.jsx
  blocks/search-results-list-block/features/search-results-list/_children/global-content.test.jsx
  blocks/search-results-list-block/features/search-results-list/_children/helpers.test.js
  blocks/search-results-list-block/features/search-results-list/_children/results-list.jsx
  blocks/search-results-list-block/features/search-results-list/_children/results-list.test.jsx
  blocks/search-results-list-block/features/search-results-list/_children/search-field.jsx
  blocks/search-results-list-block/features/search-results-list/_children/search-field.test.jsx
  blocks/search-results-list-block/features/search-results-list/_children/search-result.jsx
  blocks/search-results-list-block/features/search-results-list/_children/search-result.test.jsx
  blocks/search-results-list-block/features/search-results-list/_children/search-results-list.scss
  blocks/search-results-list-block/features/search-results-list/default.jsx
  blocks/search-results-list-block/features/search-results-list/default.test.jsx
  blocks/search-results-list-block/features/search-results-list/mock-data.js
  blocks/search-results-list-block/index.js
  blocks/search-results-list-block/index.story.jsx
  blocks/search-results-list-block/package.json
  package-lock.json
  package.json
Labels: ready for design qa

#1579 Themes 726 Migrated dividers used in non-list instances within blocks to use the divider component
  blocks/article-body-block/chains/article-body/default.jsx
  blocks/article-body-block/chains/article-body/default.test.jsx
  blocks/links-bar-block/features/links-bar/default.jsx
  blocks/links-bar-block/features/links-bar/default.test.jsx
Labels: ready for review
