Repository WPMedia/arc-themes-blocks, pull requests merged in 2022-04, with the labels that each got.

#1305 Tmedia 781 use GitHub token over pat
  .github/workflows/beta-build.yml
  .github/workflows/canary-build.yml
  .github/workflows/chromatic.yml
  .github/workflows/generate-intl-files.yml
  .github/workflows/rc-build.yml
  .github/workflows/stable-build.yml
  .github/workflows/stable-dist-tag.yml
  .github/workflows/stylelint-pr.yml
  .github/workflows/sync-themes-branch-with-themes-tag.yml
  .github/workflows/test-coverage-blocks-canary.yml
  .github/workflows/test-coverage-blocks.yml
  blocks/header-nav-chain-block/README.md
  package-lock.json
Labels: ready to merge

#1308 TBRANDS-36 - Publish Sass file
  blocks/default-output-block/package.json
Labels: ready for review

#1312 Tbrands 27 algolia assortment content source
  _templates/content-source/new/default-test.ejs.t
  blocks/algolia-assortment-content-source-block/README.md
  blocks/algolia-assortment-content-source-block/jest.config.js
  blocks/algolia-assortment-content-source-block/package-lock.json
  blocks/algolia-assortment-content-source-block/package.json
  blocks/algolia-assortment-content-source-block/sources/.npmignore
  blocks/algolia-assortment-content-source-block/sources/algolia-assortment.js
  blocks/algolia-assortment-content-source-block/sources/algolia-assortment.test.js
  package-lock.json
  package.json
Labels: ready for review, additional review

#1320 Add conditional Wrapper logic for HeadingSection
  blocks/category-carousel-block/features/category-carousel/default.jsx
Labels: ready to merge

#1313 TBRANDS-25: Category Carousel
  .storybook/themes/commerce.scss
  blocks/category-carousel-block/README.md
  blocks/category-carousel-block/_index.scss
  blocks/category-carousel-block/features/category-carousel/default.jsx
  blocks/category-carousel-block/features/category-carousel/default.test.jsx
  blocks/category-carousel-block/index.story.jsx
  blocks/category-carousel-block/intl.json
  blocks/category-carousel-block/jest.config.js
  blocks/category-carousel-block/package.json
  package-lock.json
Labels: ready to merge

#1321 Tbrands 30 update max width
  .storybook/themes/commerce.scss
  blocks/category-carousel-block/README.md
  blocks/category-carousel-block/_index.scss
  blocks/category-carousel-block/features/category-carousel/default.jsx
  blocks/category-carousel-block/features/category-carousel/default.test.jsx
  blocks/category-carousel-block/index.story.jsx
  blocks/category-carousel-block/intl.json
  blocks/category-carousel-block/jest.config.js
  blocks/category-carousel-block/package.json
  package-lock.json
Labels: feedback-pr

#1317 TBRANDS-28 => Story Carousel
  .storybook/alias/content.js
  .storybook/mock-content/storyCarousel.js
  .storybook/themes/commerce.scss
  blocks/single-column-layout-block/_index.scss
  blocks/story-carousel-block/README.md
  blocks/story-carousel-block/_index.scss
  blocks/story-carousel-block/features/.npmignore
  blocks/story-carousel-block/features/story-carousel/default.jsx
  blocks/story-carousel-block/features/story-carousel/default.test.jsx
  blocks/story-carousel-block/index.story.jsx
  blocks/story-carousel-block/intl.json
  blocks/story-carousel-block/jest.config.js
  blocks/story-carousel-block/package.json
  package-lock.json
  package.json
Labels: ready to merge
