Repository WPMedia/arc-themes-blocks, pull requests merged in 2022-08, with the labels that each got.

#1460 Add missing block-components to feature generator scss
  _templates/feature/new/scss-entry.ejs.t
Labels: ready to merge

#1459 TMEDIA-724 - Update logo alignment issues and right placement items
  .storybook/themes/news.scss
  blocks/header-nav-chain-block/_index.scss
  blocks/header-nav-chain-block/chains/header-nav-chain-block/_children/nav-logo.jsx
  blocks/header-nav-chain-block/chains/header-nav-chain-block/default.jsx
  blocks/header-nav-chain-block/index.story.jsx
Labels: ready to merge

#1463 Tmedia 716 update ads other imports
  blocks/ads-block/index.js
  blocks/gallery-block/features/gallery/default.jsx
  blocks/lead-art-block/features/leadart/default.jsx
Labels: ready for review

#1455 TMEDIA 716 refactor ads block v2
  .storybook/themes/news.scss
  blocks/ads-block/README.md
  blocks/ads-block/_index.scss
  blocks/ads-block/features/ads/_children/AdUnit/index.jsx
  blocks/ads-block/features/ads/_children/AdUnit/index.test.jsx
  blocks/ads-block/features/ads/_children/ArcAdminAd/index.jsx
  blocks/ads-block/features/ads/_children/ArcAdminAd/index.scss
  blocks/ads-block/features/ads/_children/ArcAdminAd/index.test.jsx
  blocks/ads-block/features/ads/ad-helper.js
  blocks/ads-block/features/ads/ad-helper.test.js
  blocks/ads-block/features/ads/ad-mapping.js
  blocks/ads-block/features/ads/ads.scss
  blocks/ads-block/features/ads/default.jsx
  blocks/ads-block/features/ads/default.test.jsx
  blocks/ads-block/index.js
  blocks/ads-block/index.story.jsx
  blocks/ads-block/package-lock.json
  blocks/ads-block/package.json
  blocks/gallery-block/features/gallery/default.jsx
  blocks/lead-art-block/features/leadart/default.jsx
Labels: ready to merge

#1464 TMEDIA-724 - header nav adjustments
  blocks/header-nav-chain-block/chains/header-nav-chain-block/default.jsx
Labels: ready to merge

#1466 CHORE remove unused large promo, chains styles, helpers
  blocks/shared-styles/_children/promos/large/index.jsx
  blocks/shared-styles/_children/promos/large/index.test.jsx
  blocks/shared-styles/_children/promos/large/mock-data.js
  blocks/shared-styles/index.js
  blocks/shared-styles/scss/_chains.scss
Labels: ready to merge

#1467 fix: Remove article body unused engine theme sdk prop. The value is hidden anyway.
  blocks/article-body-block/chains/article-body/default.jsx
  blocks/article-body-block/chains/article-body/default.test.jsx
Labels: ready to merge

#1461 Tmedia 755 simple list block
  .storybook/themes/news.scss
Labels: ready to merge

#1469 tmedia 926 ad sizes add
  blocks/ads-block/features/ads/ad-mapping.js
Labels: ready to merge

#1470 tmedia 926 update ads mobile
  blocks/ads-block/features/ads/ad-mapping.js
Labels: ready to merge

#1472 ci: Update typos instruction and this in generators
  _templates/chain/new/readme.ejs.t
  _templates/content-source/new/readme.ejs.t
  _templates/feature/new/readme.ejs.t
Labels: ready to merge

#1468 Tmedia 741 include label
  .storybook/mock-content/largePromo.js
  .storybook/themes/news.scss
  blocks/large-promo-block/features/large-promo/default.jsx
  blocks/large-promo-block/features/large-promo/default.test.jsx
  blocks/large-promo-block/index.story.jsx
Labels: feedback-pr

#1477 TBRANDS-101 : Product Content, Part 2
  blocks/product-content-block/README.md
  blocks/product-content-block/features/product-content/default.jsx
  blocks/product-content-block/index.story.jsx
  blocks/product-content-block/intl.json
  locale/de.json
  locale/en.json
  locale/es.json
  locale/fr.json
  locale/ja.json
  locale/ko.json
  locale/no.json
  locale/pt.json
  locale/sv.json
Labels: ready to merge

#1475 TBRANDS-100 - Update Product Information block to have sale and list price output
  .storybook/themes/commerce.scss
  blocks/product-information-block/_index.scss
  blocks/product-information-block/features/product-information/default.jsx
  blocks/product-information-block/features/product-information/default.test.jsx
  blocks/product-information-block/index.story.jsx
  blocks/product-information-block/intl.json
  blocks/product-information-block/package.json
  locale/de.json
  locale/en.json
  locale/es.json
  locale/fr.json
  locale/ja.json
  locale/ko.json
  locale/no.json
  locale/pt.json
  locale/sv.json
Labels: ready for design qa

#1447 TMEDIA-853: Alias Tokens for Headings
  .storybook/themes/commerce.scss
  .storybook/themes/news.scss
  blocks/product-assortment-carousel-block/index.story.jsx
  blocks/video-player-block/_index.scss
  blocks/video-player-block/features/video-player/default.jsx
  package-lock.json
Labels: ready to merge

#1462 Tmedia 741 no content
  .storybook/mock-content/largePromo.js
  .storybook/themes/news.scss
  blocks/global-phrases-block/intl.json
  blocks/large-promo-block/features/large-promo/default.jsx
  blocks/large-promo-block/features/large-promo/default.test.jsx
  blocks/large-promo-block/index.story.jsx
  locale/de.json
  locale/en.json
  locale/es.json
  locale/fr.json
  locale/ja.json
  locale/ko.json
  locale/no.json
  locale/pt.json
  locale/sv.json
Labels: ready for design qa

#1479 TBRANDS 116: Right rail brands max width pattern
  .storybook/themes/commerce.scss
  blocks/right-rail-advanced-block/layouts/right-rail-advanced/default.jsx
Labels: ready for review

#1486 TMEDIA-706 - Add signing service content source
  blocks/signing-service-content-source-block/README.md
  blocks/signing-service-content-source-block/jest.config.js
  blocks/signing-service-content-source-block/package.json
  blocks/signing-service-content-source-block/sources/.npmignore
  blocks/signing-service-content-source-block/sources/signing-service.js
  blocks/signing-service-content-source-block/sources/signing-service.test.js
  package.json
Labels: ready to merge

#1487 tmedia 942: Update from helper image getter for image url
  blocks/card-list-block/features/card-list/default.jsx
  blocks/extra-large-promo-block/features/extra-large-promo/default.jsx
  blocks/large-promo-block/features/large-promo/default.jsx
  blocks/numbered-list-block/features/numbered-list/default.jsx
  blocks/simple-list-block/features/simple-list/default.jsx
  blocks/small-promo-block/features/small-promo/default.jsx
  blocks/story-carousel-block/features/story-carousel/default.jsx
  package-lock.json
Labels: ready for review

#1484 TBRANDS-114 - Update to use API endpoint
  .storybook/alias/environment.js
  blocks/commerce-product-content-source-block/sources/commerce-product.js
  blocks/commerce-product-content-source-block/sources/commerce-product.test.js
  blocks/commerce-product-content-source-block/sources/mock-data.js
  blocks/product-gallery-block/features/product-gallery/default.jsx
  blocks/product-gallery-block/features/product-gallery/default.test.jsx
  blocks/product-gallery-block/index.story.jsx
  blocks/signing-service-content-source-block/sources/signing-service.js
  package-lock.json
Labels: ready to merge

#1492 TBRANDS-114 - Image Updates & Product Content Styles
  .storybook/themes/commerce.scss
  blocks/commerce-product-content-source-block/sources/mock-data.js
  blocks/product-content-block/_index.scss
  blocks/product-content-block/index.story.jsx
Labels: ready for review

#1495 Tmedia 741 video in place fix
  .storybook/themes/news.scss
  blocks/large-promo-block/features/large-promo/default.jsx
  blocks/large-promo-block/features/large-promo/default.test.jsx
  blocks/large-promo-block/index.story.jsx
Labels: ready to merge
