Repository WPMedia/arc-themes-blocks, pull requests merged in 2022-05, with the labels that each got.

#1331 TBRANDS-31 - Product Assortment Carousel Block
  .storybook/alias/content.js
  .storybook/mock-content/algoliaProduct.js
  blocks/product-assortment-carousel-block/README.md
  blocks/product-assortment-carousel-block/_index.scss
  blocks/product-assortment-carousel-block/features/product-assortment-carousel/default.jsx
  blocks/product-assortment-carousel-block/features/product-assortment-carousel/default.test.jsx
  blocks/product-assortment-carousel-block/index.story.jsx
  blocks/product-assortment-carousel-block/intl.json
  blocks/product-assortment-carousel-block/jest.config.js
  blocks/product-assortment-carousel-block/package.json
  locale/de.json
  locale/en.json
  locale/es.json
  locale/fr.json
  locale/ja.json
  locale/ko.json
  locale/no.json
  locale/pt.json
  locale/sv.json
Labels: ready to merge

#1334 Tbrands 49 single column block refactor
  .storybook/themes/commerce.scss
  blocks/single-column-layout-block/_index.scss
  blocks/single-column-layout-block/layouts/.npmignore
  blocks/single-column-layout-block/layouts/single-column-regular/default.jsx
  blocks/single-column-layout-block/layouts/single-column-regular/default.test.jsx
  blocks/single-column-layout-block/layouts/single-column-regular/index.story.jsx
  blocks/single-column-layout-block/package.json
Labels: ready for review

#1341 TBRANDS-31 - Content source logic update
  blocks/product-assortment-carousel-block/features/product-assortment-carousel/default.jsx
  blocks/product-assortment-carousel-block/index.story.jsx
Labels: ready to merge

#1339 TBRANDS-51 - Layout alignment - Quilted Image Update
  .stylelintrc.json
  blocks/quilted-image-block/_index.scss
Labels: ready for review

#1335 TMEDIA 793: Update right rail layouts
  .storybook/themes/commerce.scss
  .storybook/themes/news.scss
  blocks/right-rail-advanced-block/_index.scss
  blocks/right-rail-advanced-block/index.js
  blocks/right-rail-advanced-block/layouts/right-rail-advanced/default.jsx
  blocks/right-rail-advanced-block/layouts/right-rail-advanced/default.scss
  blocks/right-rail-advanced-block/layouts/right-rail-advanced/default.test.jsx
  blocks/right-rail-advanced-block/package.json
  blocks/right-rail-block/_index.scss
  blocks/right-rail-block/index.js
  blocks/right-rail-block/layouts/right-rail/default.jsx
  blocks/right-rail-block/layouts/right-rail/default.scss
  blocks/right-rail-block/layouts/right-rail/default.test.jsx
  blocks/right-rail-block/package.json
  package-lock.json
Labels: ready for review, additional review

#1332 TBRANDS-35: video-player-block
  .storybook/themes/commerce.scss
  .storybook/themes/news.scss
  blocks/video-player-block/_index.scss
  blocks/video-player-block/features/video-player/default.jsx
  blocks/video-player-block/features/video-player/default.scss
  blocks/video-player-block/features/video-player/default.test.jsx
  blocks/video-player-block/index.js
  blocks/video-player-block/index.story.jsx
  blocks/video-player-block/package.json
Labels: ready for review

#1343 Tmedia 727 headline block refactor
  .storybook/themes/news.scss
  blocks/headline-block/_index.scss
  blocks/headline-block/features/headline/_children/headline.jsx
  blocks/headline-block/features/headline/default.test.jsx
  blocks/headline-block/features/headline/headline.scss
  blocks/headline-block/index.js
  blocks/headline-block/package-lock.json
  blocks/headline-block/package.json
Labels: ready for review

#1350 TMEDIA-763 - Use gap
  .storybook/themes/news.scss
Labels: ready for review

#1351 Tmedia 787 news theme
  .storybook/themes/news.scss
Labels: needs changes

#1352 Update GitHub actions to allow for x.x.x branches
  .github/workflows/security-scan.yml
  .github/workflows/sync-themes-branch-with-themes-tag.yml
  .github/workflows/test-coverage-blocks-canary.yml
Labels: ready for review

#1344 TMEDIA 858 header block
  .storybook/themes/news.scss
  blocks/header-block/_index.scss
  blocks/header-block/features/header/default.jsx
  blocks/header-block/features/header/default.test.jsx
  blocks/header-block/features/header/header.scss
  blocks/header-block/index.js
  blocks/header-block/index.story.jsx
  blocks/header-block/package.json
Labels: ready for review

#1353 Video updates for badge
  .storybook/themes/commerce.scss
  .storybook/themes/news.scss
  blocks/video-player-block/features/video-player/default.jsx
Labels: ready for review

#1346 Tmedia 729 subheadline
  .storybook/themes/news.scss
  blocks/subheadline-block/_index.scss
  blocks/subheadline-block/features/subheadline/default.jsx
  blocks/subheadline-block/features/subheadline/default.test.jsx
  blocks/subheadline-block/features/subheadline/subheadline.scss
  blocks/subheadline-block/index.js
  blocks/subheadline-block/package.json
Labels: ready for review

#1345 Tmedia 763 chains
  .storybook/themes/news.scss
  blocks/double-chain-block/_index.scss
  blocks/double-chain-block/chains/double-chain/default.jsx
  blocks/double-chain-block/chains/double-chain/default.scss
  blocks/double-chain-block/chains/double-chain/default.test.jsx
  blocks/double-chain-block/index.js
  blocks/double-chain-block/package.json
  blocks/quad-chain-block/_index.scss
  blocks/quad-chain-block/chains/quad-chain/default.jsx
  blocks/quad-chain-block/chains/quad-chain/default.test.jsx
  blocks/quad-chain-block/index.js
  blocks/quad-chain-block/package.json
  blocks/single-chain-block/_index.scss
  blocks/single-chain-block/chains/single-chain/default.jsx
  blocks/single-chain-block/chains/single-chain/default.test.jsx
  blocks/single-chain-block/index.js
  blocks/single-chain-block/package-lock.json
  blocks/single-chain-block/package.json
  blocks/triple-chain-block/_index.scss
  blocks/triple-chain-block/chains/triple-chain/default.jsx
  blocks/triple-chain-block/chains/triple-chain/default.test.jsx
  blocks/triple-chain-block/index.js
  blocks/triple-chain-block/package.json
Labels: ready to merge

#1356 Sync border radius changes
  .storybook/themes/commerce.scss
  .storybook/themes/news.scss
Labels: ready for review

#1362 Tmedia 732 fix import tests side effects
  blocks/byline-block/README.md
  blocks/extra-large-promo-block/package.json
  blocks/large-promo-block/package.json
  blocks/medium-promo-block/package.json
  blocks/results-list-block/package.json
  blocks/search-results-list-block/features/search-results-list/_children/custom-content.jsx
  blocks/search-results-list-block/features/search-results-list/_children/custom-content.test.jsx
  blocks/search-results-list-block/features/search-results-list/_children/global-content.jsx
  blocks/search-results-list-block/features/search-results-list/_children/global-content.test.jsx
Labels: ready for review
