Repository WPMedia/arc-themes-blocks, pull requests merged in 2022-10, with the labels that each got.

#1519 ci: Update the package-lock to use the correct dependencies in the lockfile
  blocks/card-list-block/package-lock.json
  blocks/category-carousel-block/package-lock.json
  blocks/commerce-product-content-source-block/package-lock.json
  blocks/date-block/package-lock.json
  blocks/double-chain-block/package-lock.json
  blocks/event-tester-block/package-lock.json
  blocks/global-phrases-block/package-lock.json
  blocks/header-block/package-lock.json
  blocks/header-nav-block/package-lock.json
  blocks/hero-block/package-lock.json
  blocks/htmlbox-block/package-lock.json
  blocks/large-manual-promo-block/package-lock.json
  blocks/lead-art-block/package-lock.json
  blocks/links-bar-block/package-lock.json
  blocks/masthead-block/package-lock.json
  blocks/medium-manual-promo-block/package-lock.json
  blocks/medium-promo-block/package-lock.json
  blocks/numbered-list-block/package-lock.json
  blocks/overline-block/package-lock.json
  blocks/placeholder-image-block/package-lock.json
  blocks/product-assortment-carousel-block/package-lock.json
  blocks/product-content-block/package-lock.json
  blocks/product-featured-image-block/package-lock.json
  blocks/product-gallery-block/package-lock.json
  blocks/product-information-block/package-lock.json
  blocks/quad-chain-block/package-lock.json
  blocks/quilted-image-block/package-lock.json
  blocks/resizer-image-block/package-lock.json
  blocks/resizer-image-content-source-block/package-lock.json
  blocks/results-list-block/package-lock.json
  blocks/right-rail-advanced-block/package-lock.json
  blocks/right-rail-block/package-lock.json
  blocks/search-content-source-block/package-lock.json
  blocks/search-results-list-block/package-lock.json
  blocks/share-bar-block/package-lock.json
  blocks/shared-styles/package-lock.json
  blocks/signing-service-content-source-block/package-lock.json
  blocks/simple-list-block/package-lock.json
  blocks/single-column-layout-block/package-lock.json
  blocks/site-hierarchy-content-block/package-lock.json
  blocks/small-manual-promo-block/package-lock.json
  blocks/small-promo-block/package-lock.json
  blocks/story-carousel-block/package-lock.json
  blocks/story-feed-query-content-source-block/package-lock.json
  blocks/tag-title-block/package-lock.json
  blocks/tags-content-source-block/package-lock.json
  blocks/textfile-block/package-lock.json
  blocks/top-table-list-block/package-lock.json
  blocks/triple-chain-block/package-lock.json
  blocks/unpublished-content-source-block/package-lock.json
  blocks/video-promo-block/package-lock.json
Labels: ready to merge

#1518 ci: Remove references to unused branches for release. Clean up actions
  .github/workflows/beta-build.yml
  .github/workflows/canary-build.yml
  .github/workflows/delete-unused-canary-packages.yml
  .github/workflows/rc-build.yml
  .github/workflows/security-scan.yml
  .github/workflows/stable-build.yml
  .github/workflows/stylelint-pr.yml
  .github/workflows/test-coverage-blocks-canary.yml
  .github/workflows/test-coverage-blocks.yml
Labels: ready to merge

#1520 TBRANDS-66 - Asset key change
  blocks/commerce-product-content-source-block/sources/mock-data.js
  blocks/product-featured-image-block/features/product-featured-image/default.jsx
  blocks/product-featured-image-block/features/product-featured-image/default.test.jsx
  blocks/product-gallery-block/features/product-gallery/default.jsx
  blocks/product-gallery-block/features/product-gallery/default.test.jsx
Labels: ready to merge

#1525 tbrands 67: Product Featured featured image toggle bug
  blocks/product-gallery-block/features/product-gallery/default.jsx
Labels: ready for review

#1526 Tbrands 67 product gallery featured image 2.0.2
  blocks/product-gallery-block/features/product-gallery/default.jsx
Labels: ready for review

#1527 Tmedia 962 update large image size
  blocks/resizer-image-block/ratiosFor.js
  blocks/resizer-image-block/ratiosFor.test.js
Labels: ready to merge

#1530 tmedia 962 Fix update tests new sizes
  .storybook/mock-content/largePromo.js
  blocks/large-promo-block/features/large-promo/default.jsx
  blocks/shared-styles/_children/promos/large/index.test.jsx
  package-lock.json
  package.json
Labels: ready to merge

#1528 Tbrands 110 product assortment algolia
  .storybook/mock-content/algoliaProduct.js
  blocks/product-assortment-carousel-block/README.md
  blocks/product-assortment-carousel-block/features/product-assortment-carousel/default.jsx
  blocks/product-assortment-carousel-block/features/product-assortment-carousel/default.test.jsx
Labels: ready to merge

#1532 Docs update available commands
  .eslintignore
  .github/workflows/sync-themes-branch-with-themes-tag.yml
  .github/workflows/test-coverage-blocks.yml
  .gitignore
  README.md
  components/.gitkeep
  lerna.json
  package.json
Labels: WIP, small-improvement

#1534 Docs on generators actions linting
  .eslintignore
  .github/workflows/arc-themes-base-to-new-tag.yml
  .github/workflows/sync-themes-branch-with-themes-tag.yml
  .husky/pre-push
  .prettierignore
  .stylelintignore
  .vscode/extensions.json
  README.md
  package.json
Labels: ready for review, small-improvement

#1535 Tbrands 110 image featured algolia
  .eslintignore
  .storybook/mock-content/algoliaProduct.js
  blocks/product-assortment-carousel-block/README.md
  blocks/product-assortment-carousel-block/features/product-assortment-carousel/default.jsx
  blocks/product-assortment-carousel-block/features/product-assortment-carousel/default.test.jsx
  package-lock.json
Labels: ready for review

#1538 TBRANDS-110 - Logic update for data lookups
  blocks/product-assortment-carousel-block/features/product-assortment-carousel/default.jsx
  blocks/product-assortment-carousel-block/features/product-assortment-carousel/default.test.jsx
Labels: ready to merge

#1539 Add data-chromatic='ignore' to image in header nav
  blocks/header-nav-chain-block/chains/header-nav-chain-block/_children/nav-logo.jsx
  blocks/header-nav-chain-block/index.story.jsx
  resources/100x100.gif
  resources/100x800.gif
  resources/1200x150.gif
  resources/86x36.gif
Labels: ready to merge

#1536 TMEDIA-707 : Update content sources for image resizer
  blocks/collections-content-source-block/package.json
  blocks/collections-content-source-block/sources/content-api-collections.js
  blocks/collections-content-source-block/sources/content-api-collections.test.js
  blocks/content-api-source-block/package.json
  blocks/content-api-source-block/sources/content-api.js
  blocks/content-api-source-block/sources/content-api.test.js
  blocks/related-content-content-source-block/package.json
  blocks/related-content-content-source-block/sources/related-content.js
  blocks/related-content-content-source-block/sources/related-content.test.js
  blocks/search-content-source-block/package.json
  blocks/search-content-source-block/sources/search-api.js
  blocks/search-content-source-block/sources/search-api.test.js
  blocks/signing-service-content-source-block/index.js
  blocks/unpublished-content-source-block/package.json
  blocks/unpublished-content-source-block/sources/content-api-unpublished.js
  blocks/unpublished-content-source-block/sources/content-api-unpublished.test.js
  package-lock.json
  package.json
Labels: ready to merge

#1540 Tmedia 934
  blocks/article-body-block/chains/article-body/default.jsx
  blocks/article-body-block/chains/article-body/default.test.jsx
  blocks/article-body-block/chains/article-body/shared/get-resize-params-from-ans-image.js
  blocks/article-body-block/chains/article-body/shared/get-resize-params-from-ans-image.test.js
  blocks/article-body-block/index.story.jsx
  blocks/content-api-source-block/sources/content-api.js
  blocks/content-api-source-block/sources/content-api.test.js
Labels: ready to merge

#1521 TBRANDS-106 & TBRANDS-126 : Product Gallery Desktop View
  .storybook/themes/commerce.scss
  blocks/product-gallery-block/_index.scss
  blocks/product-gallery-block/features/product-gallery/_children/MainImage/index.jsx
  blocks/product-gallery-block/features/product-gallery/_children/MainImage/index.test.jsx
  blocks/product-gallery-block/features/product-gallery/_children/ProductFocusView/index.jsx
  blocks/product-gallery-block/features/product-gallery/_children/ProductFocusView/index.test.jsx
  blocks/product-gallery-block/features/product-gallery/_children/ThumbnailBar/index.jsx
  blocks/product-gallery-block/features/product-gallery/_children/ThumbnailBar/index.test.jsx
  blocks/product-gallery-block/features/product-gallery/default.jsx
  blocks/product-gallery-block/features/product-gallery/mock-data.js
  blocks/product-gallery-block/intl.json
  locale/de.json
  locale/en.json
  locale/es.json
  locale/fr.json
  locale/ja.json
  locale/ko.json
  locale/no.json
  locale/pt.json
  locale/sv.json
Labels: ready for review
