Repository WPMedia/arc-themes-blocks, pull requests merged in 2022-09, with the labels that each got.

#1491 Tmedia 734 gallery block update
  .storybook/themes/news.scss
  blocks/gallery-block/README.md
  blocks/gallery-block/_index.scss
  blocks/gallery-block/features/.npmignore
  blocks/gallery-block/features/gallery/default.jsx
  blocks/gallery-block/features/gallery/default.test.jsx
  blocks/gallery-block/index.js
  blocks/gallery-block/index.story.jsx
  blocks/gallery-block/package-lock.json
  blocks/gallery-block/package.json
  blocks/global-phrases-block/intl.json
  locale/en.json
  locale/no.json
  locale/pt.json
Labels: ready to merge

#1500 chore: Remove locale en as that's the default with themes settings
  blocks/article-body-block/chains/article-body/default.jsx
  blocks/author-bio-block/features/author-bio/default.jsx
  blocks/category-carousel-block/features/category-carousel/default.jsx
  blocks/default-output-block/output-types/__tests__/default.test.jsx
  blocks/default-output-block/output-types/default.jsx
  blocks/footer-block/features/footer/default.jsx
  blocks/footer-block/features/footer/default.test.jsx
  blocks/full-author-bio-block/features/full-author-bio/default.jsx
  blocks/header-nav-chain-block/chains/header-nav-chain-block/_children/nav-links/default.jsx
  blocks/header-nav-chain-block/chains/header-nav-chain-block/_children/search-box.jsx
  blocks/header-nav-chain-block/chains/header-nav-chain-block/_children/section-nav.jsx
  blocks/header-nav-chain-block/chains/header-nav-chain-block/default.jsx
  blocks/search-results-list-block/features/search-results-list/_children/custom-content.jsx
  blocks/search-results-list-block/features/search-results-list/_children/custom-content.test.jsx
  blocks/search-results-list-block/features/search-results-list/_children/global-content.jsx
  blocks/search-results-list-block/features/search-results-list/_children/global-content.test.jsx
  blocks/share-bar-block/features/share-bar/default.jsx
Labels: ready for review, small-improvement

#1474 Tmedia 717 author bio block refactor
  .storybook/themes/news.scss
  blocks/author-bio-block/README.md
  blocks/author-bio-block/_index.scss
  blocks/author-bio-block/features/author-bio/author-bio.scss
  blocks/author-bio-block/features/author-bio/default.jsx
  blocks/author-bio-block/features/author-bio/default.test.jsx
  blocks/author-bio-block/intl.json
  blocks/author-bio-block/package-lock.json
  blocks/author-bio-block/package.json
  blocks/global-phrases-block/intl.json
  locale/de.json
  locale/en.json
  locale/es.json
  locale/fr.json
  locale/ja.json
  locale/ko.json
  locale/no.json
  locale/pt.json
  locale/sv.json
Labels: ready to merge

#1482 TMEDIA-758: Full Author Bio
  .storybook/themes/news.scss
  blocks/author-bio-block/package.json
  blocks/author-content-source-block/index.js
  blocks/author-content-source-block/package-lock.json
  blocks/author-content-source-block/sources/author-api.js
  blocks/full-author-bio-block/README.md
  blocks/full-author-bio-block/_index.scss
  blocks/full-author-bio-block/features/full-author-bio/_children/Presentation/index.jsx
  blocks/full-author-bio-block/features/full-author-bio/_children/Presentation/index.test.jsx
  blocks/full-author-bio-block/features/full-author-bio/default.jsx
  blocks/full-author-bio-block/features/full-author-bio/default.test.jsx
  blocks/full-author-bio-block/features/full-author-bio/full-author-bio.scss
  blocks/full-author-bio-block/index.js
  blocks/full-author-bio-block/index.story.jsx
  blocks/full-author-bio-block/package-lock.json
  blocks/full-author-bio-block/package.json
Labels: ready for design qa

#1481 TMEDIA-742 : Medium Promo block
  .storybook/mock-content/mediumPromo.js
  .storybook/themes/news.scss
  blocks/medium-promo-block/README.md
  blocks/medium-promo-block/_index.scss
  blocks/medium-promo-block/features/medium-promo/default.jsx
  blocks/medium-promo-block/features/medium-promo/default.test.jsx
  blocks/medium-promo-block/features/medium-promo/mock-data.js
  blocks/medium-promo-block/index.js
  blocks/medium-promo-block/package.json
Labels: ready to merge

#1496 TMEDIA 725: Convert Footer block
  .storybook/alias/properties.js
  .storybook/themes/news.scss
  blocks/footer-block/README.md
  blocks/footer-block/_index.scss
  blocks/footer-block/features/.npmignore
  blocks/footer-block/features/footer/_children/link.jsx
  blocks/footer-block/features/footer/_children/link_node.test.jsx
  blocks/footer-block/features/footer/default.jsx
  blocks/footer-block/features/footer/default.test.jsx
  blocks/footer-block/features/footer/footer.scss
  blocks/footer-block/index.js
  blocks/footer-block/index.story.mdx
  blocks/footer-block/package-lock.json
  blocks/footer-block/package.json
Labels: ready for design qa

#1506 updated max-height and max-width of author image to 88px
  .storybook/themes/news.scss
Labels: ready to merge, ready for design qa

#1509 TMEDIA-725: Fix footer links font
  .storybook/themes/news.scss
Labels: ready to merge

#1510 Add additional logic to check product data value
  blocks/product-content-block/features/product-content/default.jsx
  blocks/product-content-block/features/product-content/default.test.jsx
Labels: ready to merge

#1511 fixed image update from imageURL
  blocks/extra-large-promo-block/features/extra-large-promo/default.jsx
  blocks/large-promo-block/features/large-promo/default.jsx
  blocks/medium-promo-block/features/medium-promo/default.jsx
Labels: ready to merge

#1512 Tmedia 758 fix link
  blocks/full-author-bio-block/features/full-author-bio/_children/Presentation/index.jsx
  blocks/full-author-bio-block/features/full-author-bio/_children/Presentation/index.test.jsx
  blocks/full-author-bio-block/features/full-author-bio/default.jsx
Labels: ready to merge

#1513 TBRANDS 65 carousel thumbnail for product gallery
  .storybook/themes/commerce.scss
  blocks/product-gallery-block/README.md
  blocks/product-gallery-block/_index.scss
  blocks/product-gallery-block/features/product-gallery/default.jsx
  blocks/product-gallery-block/features/product-gallery/default.test.jsx
  blocks/product-gallery-block/index.story.jsx
  blocks/product-gallery-block/intl.json
  locale/de.json
  locale/en.json
  locale/es.json
  locale/fr.json
  locale/ja.json
  locale/ko.json
  locale/no.json
  locale/pt.json
  locale/sv.json
  package-lock.json
Labels: dependencies, ready to merge

#1516 TBRANDS-112: Add resizer options to Product Featured Image
  blocks/product-featured-image-block/features/product-featured-image/default.jsx
  blocks/product-featured-image-block/features/product-featured-image/default.test.jsx
  blocks/product-featured-image-block/index.story.jsx
Labels: ready for review
