Repository WPMedia/arc-themes-blocks, pull requests merged in 2022-06, with the labels that each got.

#1366 TMEDIA-726 - Masthead Block v2
  .storybook/themes/news.scss
  _templates/feature/new/package.ejs.t
  blocks/masthead-block/README.md
  blocks/masthead-block/_index.scss
  blocks/masthead-block/features/masthead-block/_children/GenericDivider.js
  blocks/masthead-block/features/masthead-block/_children/HeaderContainerHideMobile.js
  blocks/masthead-block/features/masthead-block/_children/HeightConstrainedImageContainer.js
  blocks/masthead-block/features/masthead-block/_children/MastheadItemsContainer.js
  blocks/masthead-block/features/masthead-block/default.jsx
  blocks/masthead-block/features/masthead-block/default.test.jsx
  blocks/masthead-block/features/masthead-block/masthead-block.scss
  blocks/masthead-block/index.js
  blocks/masthead-block/package.json
Labels: ready for review

#1369 TMEDIA-869 - Update input spacing as per designs
  .storybook/themes/commerce.scss
  .storybook/themes/news.scss
Labels: ready to merge

#1374 TBRANDS-61 : Add a Full-Width Section to the Single Column Regular Width Layout
  blocks/single-column-layout-block/README.md
  blocks/single-column-layout-block/_index.scss
  blocks/single-column-layout-block/layouts/single-column-regular/default.jsx
  blocks/single-column-layout-block/layouts/single-column-regular/default.test.jsx
  blocks/single-column-layout-block/layouts/single-column-regular/index.story.jsx
Labels: ready to merge

#1373 TMEDIA-730 - Article body block
  .storybook/themes/news.scss
  blocks/article-body-block/README.md
  blocks/article-body-block/_index.scss
  blocks/article-body-block/chains/article-body/_articlebody.scss
  blocks/article-body-block/chains/article-body/_children/heading.jsx
  blocks/article-body-block/chains/article-body/_children/heading.test.jsx
  blocks/article-body-block/chains/article-body/_children/html.jsx
  blocks/article-body-block/chains/article-body/_children/list.jsx
  blocks/article-body-block/chains/article-body/_children/list.test.jsx
  blocks/article-body-block/chains/article-body/_children/oembed.jsx
  blocks/article-body-block/chains/article-body/_children/oembed.test.jsx
  blocks/article-body-block/chains/article-body/_children/quote.jsx
  blocks/article-body-block/chains/article-body/_children/quote.test.jsx
  blocks/article-body-block/chains/article-body/_children/table.jsx
  blocks/article-body-block/chains/article-body/_children/table.test.jsx
  blocks/article-body-block/chains/article-body/default.jsx
  blocks/article-body-block/chains/article-body/default.test.jsx
  blocks/article-body-block/index.js
  blocks/article-body-block/index.story.jsx
  blocks/article-body-block/package.json
  package-lock.json
Labels: ready to merge

#1376 Add additional stories for header nav chain
  blocks/header-nav-chain-block/headerNavMock.js
  blocks/header-nav-chain-block/index.story.jsx
Labels: ready to merge

#1371 TMEDIA-721: Alert Bar Block
  .storybook/themes/commerce.scss
  .storybook/themes/news.scss
  blocks/alert-bar-block/_index.scss
  blocks/alert-bar-block/features/alert-bar/alert-bar.scss
  blocks/alert-bar-block/features/alert-bar/default.jsx
  blocks/alert-bar-block/features/alert-bar/default.test.jsx
  blocks/alert-bar-block/index.js
  blocks/alert-bar-block/index.story.jsx
  blocks/alert-bar-block/package.json
  blocks/alert-bar-content-source-block/package-lock.json
  blocks/alert-bar-content-source-block/package.json
  blocks/alert-bar-content-source-block/sources/alert-bar-collections.test.js
  package-lock.json
  package.json
Labels: ready to merge

#1357 Tmedia 722 links bar block refactor
  .storybook/preview-head.html
  .storybook/themes/news.scss
  blocks/footer-block/features/footer/_children/link.jsx
  blocks/footer-block/features/footer/_children/link_node.test.jsx
  blocks/footer-block/features/footer/default.jsx
  blocks/links-bar-block/_index.scss
  blocks/links-bar-block/features/links-bar/_children/link.jsx
  blocks/links-bar-block/features/links-bar/_children/link_node.test.jsx
  blocks/links-bar-block/features/links-bar/default.jsx
  blocks/links-bar-block/features/links-bar/default.test.jsx
  blocks/links-bar-block/features/links-bar/links-bar.scss
  blocks/links-bar-block/index.js
  blocks/links-bar-block/package.json
Labels: needs changes

#1379 TMEDIA-726 - Tagline - Align Center
  .storybook/themes/news.scss
Labels: ready to merge

#1380 TMEDIA-726 tagline center 2
  .storybook/themes/news.scss
  blocks/masthead-block/index.story.jsx
Labels: ready to merge

#1378 TMEDIA 722 Links bar cleanup
  blocks/links-bar-block/README.md
  blocks/links-bar-block/_index.scss
  blocks/links-bar-block/package-lock.json
  blocks/links-bar-block/package.json
Labels: ready to merge

#1381 TMEDIA-737: Tag Title block
  .storybook/themes/news.scss
  blocks/tag-title-block/README.md
  blocks/tag-title-block/_index.scss
  blocks/tag-title-block/features/tag-title/default.jsx
  blocks/tag-title-block/features/tag-title/default.test.jsx
  blocks/tag-title-block/features/tag-title/tag-title.scss
  blocks/tag-title-block/index.js
  blocks/tag-title-block/package.json
Labels: ready to merge

#1383 TBRANDS-61 - Add hook for main element
  blocks/single-column-layout-block/_index.scss
Labels: ready for review

#1397 Tmeda 747 small promo image link
  .storybook/themes/news.scss
  blocks/small-manual-promo-block/features/small-manual-promo/default.jsx
  blocks/small-manual-promo-block/features/small-manual-promo/default.test.jsx
Labels: ready for review

#1396 TMEDIA-744: Extra Large Manual Promo
  .storybook/themes/news.scss
  blocks/extra-large-manual-promo-block/README.md
  blocks/extra-large-manual-promo-block/_index.scss
  blocks/extra-large-manual-promo-block/features/extra-large-manual-promo/default.jsx
  blocks/extra-large-manual-promo-block/features/extra-large-manual-promo/default.test.jsx
  blocks/extra-large-manual-promo-block/index.js
  blocks/extra-large-manual-promo-block/package-lock.json
  blocks/extra-large-manual-promo-block/package.json
  package-lock.json
Labels: needs changes
