Repository WPMedia/arc-themes-blocks, pull requests merged in 2022-11, with the labels that each got.

#1542 TMEDIA-707 - Change content api content source back to ans-item schema name
  blocks/content-api-source-block/sources/content-api.js
Labels: ready to merge

#1543 TBRANDS-129 - Design review feedback
  .storybook/themes/commerce.scss
  blocks/product-gallery-block/features/product-gallery/_children/ProductFocusView/index.jsx
  blocks/product-gallery-block/features/product-gallery/_children/ProductFocusView/index.test.jsx
  blocks/product-gallery-block/features/product-gallery/_children/ThumbnailBar/index.jsx
  blocks/product-gallery-block/features/product-gallery/_children/ThumbnailBar/index.test.jsx
Labels: ready to merge

#1545 TMEDIA-938 - Extra large promo image updates
  .storybook/mock-content/extraLargePromo.js
  blocks/extra-large-promo-block/features/extra-large-promo/default.jsx
  blocks/extra-large-promo-block/features/extra-large-promo/default.test.jsx
  blocks/extra-large-promo-block/features/extra-large-promo/mock-data.js
  package-lock.json
  package.json
Labels: ready for review

#1546 TBRANDS-129 - Feedback
  .storybook/themes/commerce.scss
  blocks/product-gallery-block/features/product-gallery/_children/ThumbnailBar/index.jsx
Labels: ready to merge

#1547 TMEDIA-967 - Move top level alias map to $tokens.default
  .storybook/themes/commerce.scss
  .storybook/themes/news.scss
Labels: ready to merge

#1551 Tmedia 939 large promo block resizer
  .storybook/mock-content/largePromo.js
  blocks/large-promo-block/features/large-promo/default.jsx
  blocks/large-promo-block/features/large-promo/default.test.jsx
  blocks/large-promo-block/index.story.jsx
Labels: ready to merge

#1555 Update small promo to use resizer v2
  .storybook/mock-content/smallPromo.js
  blocks/small-promo-block/features/small-promo/default.jsx
  blocks/small-promo-block/features/small-promo/default.test.jsx
  blocks/small-promo-block/features/small-promo/mock-data.js
  jest/mocks/environment.js
Labels: ready to merge

#1552 THEMES-739 top table list v2
  .storybook/mock-content/topTableList.js
  .storybook/themes/news.scss
  blocks/extra-large-promo-block/features/extra-large-promo/default.jsx
  blocks/large-promo-block/features/large-promo/default.jsx
  blocks/shared-styles/_children/promos/medium/index.jsx
  blocks/shared-styles/_children/promos/medium/index.test.jsx
  blocks/shared-styles/_children/promos/medium/mock-data.js
  blocks/shared-styles/index.js
  blocks/shared-styles/scss/_extra-large-promo.scss
  blocks/shared-styles/scss/_large-promo.scss
  blocks/shared-styles/scss/_medium-promo.scss
  blocks/shared-styles/scss/_small-promo.scss
  blocks/top-table-list-block/README.md
  blocks/top-table-list-block/_index.scss
  blocks/top-table-list-block/features/top-table-list/_children/conditional-story-item.jsx
  blocks/top-table-list-block/features/top-table-list/_children/conditional-story-item.test.jsx
  blocks/top-table-list-block/features/top-table-list/_children/extra-large.jsx
  blocks/top-table-list-block/features/top-table-list/_children/extra-large.test.jsx
  blocks/top-table-list-block/features/top-table-list/_children/horizontal-overline-image-story-item.jsx
  blocks/top-table-list-block/features/top-table-list/_children/horizontal-overline-image-story-item.test.jsx
  blocks/top-table-list-block/features/top-table-list/_children/large.jsx
  blocks/top-table-list-block/features/top-table-list/_children/large.test.jsx
  blocks/top-table-list-block/features/top-table-list/_children/medium-list-item.jsx
  blocks/top-table-list-block/features/top-table-list/_children/medium-list-item.test.jsx
  blocks/top-table-list-block/features/top-table-list/_children/medium.jsx
  blocks/top-table-list-block/features/top-table-list/_children/medium.test.jsx
  blocks/top-table-list-block/features/top-table-list/_children/small-list-item.jsx
  blocks/top-table-list-block/features/top-table-list/_children/small-list-item.test.jsx
  blocks/top-table-list-block/features/top-table-list/_children/small.jsx
  blocks/top-table-list-block/features/top-table-list/_children/small.test.jsx
  blocks/top-table-list-block/features/top-table-list/_children/vertical-overline-image-story-item.jsx
  blocks/top-table-list-block/features/top-table-list/_children/vertical-overline-image-story-item.test.jsx
  blocks/top-table-list-block/features/top-table-list/default.jsx
  blocks/top-table-list-block/features/top-table-list/default.scss
  blocks/top-table-list-block/features/top-table-list/default.test.jsx
  blocks/top-table-list-block/features/top-table-list/shared/imagePositionConstants.js
  blocks/top-table-list-block/features/top-table-list/shared/imageRatioCustomField.js
  blocks/top-table-list-block/index.js
  blocks/top-table-list-block/index.story.jsx
  blocks/top-table-list-block/mock-data.js
  blocks/top-table-list-block/package.json
Labels: ready for review, ready for design qa
