Repository WPMedia/arc-themes-blocks, pull requests merged in 2023-11, with the labels that each got.

#1767 THEMES-1474: Input display bug
  .storybook/themes/news.scss
  blocks/identity-block/themes/commerce.json
  blocks/identity-block/themes/news.json
  blocks/search-results-list-block/themes/news.json
Labels: ready for review, review in progress

#1747 DAM-7996
  blocks/article-body-block/chains/article-body/default.jsx
  blocks/article-body-block/chains/article-body/default.test.jsx
  blocks/lead-art-block/features/leadart/default.jsx
  blocks/lead-art-block/features/leadart/default.test.jsx
  blocks/product-gallery-block/README.md
  blocks/video-player-block/features/video-player/default.jsx
Labels: question, additional review, ready for design qa

#1768 Subscriptions blocks v2
  blocks/identity-block/features/signup/default.jsx
  blocks/identity-block/index.js
  blocks/subscriptions-block/README.md
  blocks/subscriptions-block/_index.scss
  blocks/subscriptions-block/components/Cart/index.jsx
  blocks/subscriptions-block/components/Cart/index.test.jsx
  blocks/subscriptions-block/components/Cart/item.jsx
  blocks/subscriptions-block/components/Cart/item.test.jsx
  blocks/subscriptions-block/components/ContactInfo/countryCodes.js
  blocks/subscriptions-block/components/ContactInfo/google.svg
  blocks/subscriptions-block/components/ContactInfo/index.jsx
  blocks/subscriptions-block/components/ContactInfo/index.story-ignore.jsx
  blocks/subscriptions-block/components/ContactInfo/index.test.jsx
  blocks/subscriptions-block/components/OfferCard/index.jsx
  blocks/subscriptions-block/components/OfferCard/index.story-ignore.jsx
  blocks/subscriptions-block/components/OfferCard/index.test.jsx
  blocks/subscriptions-block/components/OfferToProductList/index.jsx
  blocks/subscriptions-block/components/OfferToProductList/index.test.jsx
  blocks/subscriptions-block/components/PaymentForm/index.jsx
  blocks/subscriptions-block/components/PaymentForm/index.story-ignore.jsx
  blocks/subscriptions-block/components/PaymentForm/index.test.jsx
  blocks/subscriptions-block/components/useOffer.jsx
  blocks/subscriptions-block/components/useOffer.test.jsx
  blocks/subscriptions-block/components/useSales.jsx
  blocks/subscriptions-block/components/useSales.test.jsx
  blocks/subscriptions-block/features/checkout/_children/PaymentInfo/index.jsx
  blocks/subscriptions-block/features/checkout/default.jsx
  blocks/subscriptions-block/features/checkout/default.test.jsx
  blocks/subscriptions-block/features/offer/default.jsx
  blocks/subscriptions-block/features/offer/default.test.jsx
  blocks/subscriptions-block/intl.json
  blocks/subscriptions-block/jest.config.js
  blocks/subscriptions-block/package-lock.json
  blocks/subscriptions-block/package.json
  blocks/subscriptions-block/themes/commerce.json
  blocks/subscriptions-block/themes/news.json
  blocks/subscriptions-block/utils/currency.js
  blocks/subscriptions-block/utils/currency.test.jsx
  locale/de.json
  locale/en.json
  locale/es.json
  locale/fr.json
  locale/ja.json
  locale/ko.json
  locale/no.json
  locale/pt.json
  locale/sv.json
  package.json
Labels: ready to merge

#1797 add index.js to included files in identity package.json
  blocks/identity-block/package.json
Labels: ready for review

#1798 empty commit to force a publish of identity & subs blocks
  blocks/identity-block/features/login/default.jsx
  blocks/identity-block/index.js
  blocks/subscriptions-block/features/offer/default.jsx
Labels: ready for review

#1792 Added option object to respect session across tabs
  blocks/identity-block/features/login/default.jsx
Labels: ready to merge

#1802 ASUB-7841 Subscriptions Paywall - migrating from v1 to v2
  blocks/subscriptions-block/_index.scss
  blocks/subscriptions-block/components/PaywallOffer/index.jsx
  blocks/subscriptions-block/components/PaywallOffer/index.test.js
  blocks/subscriptions-block/components/RegwallOffer/index.jsx
  blocks/subscriptions-block/components/RegwallOffer/index.test.js
  blocks/subscriptions-block/components/SubscriptionDialog/index.jsx
  blocks/subscriptions-block/components/SubscriptionDialog/index.story.jsx
  blocks/subscriptions-block/components/SubscriptionDialog/index.test.js
  blocks/subscriptions-block/components/SubscriptionOverlay/index.jsx
  blocks/subscriptions-block/components/SubscriptionOverlay/index.story.jsx
  blocks/subscriptions-block/components/SubscriptionOverlay/index.test.jsx
  blocks/subscriptions-block/components/usePaywall.js
  blocks/subscriptions-block/components/usePaywall.test.js
  blocks/subscriptions-block/features/paywall/default.jsx
  blocks/subscriptions-block/features/paywall/default.test.jsx
  blocks/subscriptions-block/themes/news.json
Labels: ready to merge

#1803 OIDC for login block and social sign in
  blocks/identity-block/components/login/index.jsx
  blocks/identity-block/components/social-sign-on/index.jsx
  blocks/identity-block/components/social-sign-on/utils/useSocialSignIn.js
  blocks/identity-block/features/login/default.jsx
  blocks/identity-block/features/social-sign-on/default.jsx
  blocks/identity-block/utils/useOIDCLogin.jsx
Labels: ready for review

#1808 Fixing issues on Identity and Subs blocks
  blocks/identity-block/components/social-sign-on/utils/useSocialSignIn.js
  blocks/identity-block/features/login/default.jsx
  blocks/subscriptions-block/components/ContactInfo/google.svg
  blocks/subscriptions-block/components/ContactInfo/index.jsx
  blocks/subscriptions-block/components/OfferCard/index.jsx
  blocks/subscriptions-block/utils/currency.js
Labels: review in progress
