Repository WPMedia/arc-themes-blocks, pull requests merged in 2023-08, with the labels that each got.

#1712 THEMES-1173: header nav | Update button component to match new design
  .storybook/themes/news.scss
  blocks/header-nav-chain-block/themes/news.json
Labels: ready for review

#1713 THEMES-760: Identity Blocks | Login links block
  blocks/identity-block/_index.scss
  blocks/identity-block/features/login-links/default.jsx
  blocks/identity-block/features/login-links/default.test.jsx
  blocks/identity-block/features/login-links/index.story-ignore.jsx
  blocks/identity-block/intl.json
  blocks/identity-block/themes/news.json
  blocks/single-column-layout-block/themes/commerce.json
  blocks/single-column-layout-block/themes/news.json
  locale/en.json
  package-lock.json
Labels: ready for review

#1716 THEMES-1322 - fix: lead art gallery aspect ratio
  .storybook/themes/news.scss
  blocks/lead-art-block/features/leadart/default.jsx
  blocks/lead-art-block/themes/news.json
Labels: ready for design qa

#1717 THEMES-762: Identity Blocks | Reset Password block
  blocks/identity-block/_index.scss
  blocks/identity-block/components/form-password-confirm/index.test.jsx
  blocks/identity-block/components/headlined-submit-form/index.jsx
  blocks/identity-block/components/identity/index.test.jsx
  blocks/identity-block/components/login/index.jsx
  blocks/identity-block/features/login/default.test.jsx
  blocks/identity-block/features/reset-password/default.jsx
  blocks/identity-block/features/reset-password/default.story-ignore.jsx
  blocks/identity-block/features/reset-password/default.test.jsx
  blocks/identity-block/features/signup/default.test.jsx
  blocks/identity-block/themes/commerce.json
  blocks/identity-block/themes/news.json
  blocks/identity-block/utils/validate-redirect-url.js
  blocks/identity-block/utils/validate-redirect-url.test.js
Labels: ready for review, review in progress

#1719 THEMES-763: Identity Blocks | Forgot Password Block
  blocks/identity-block/_index.scss
  blocks/identity-block/components/identity/index.test.jsx
  blocks/identity-block/features/forgot-password/default.jsx
  blocks/identity-block/features/forgot-password/default.story-ignore.jsx
  blocks/identity-block/features/forgot-password/default.test.jsx
  blocks/identity-block/themes/news.json
Labels: ready to merge

#1718 THEMES-1276 Updated color-primary to blue-6
  .storybook/themes/commerce.scss
  .storybook/themes/news.scss
  blocks/alias-tokens/themes/commerce.json
  blocks/alias-tokens/themes/news.json
  blocks/extra-large-promo-block/_index.scss
  blocks/identity-block/_index.scss
  blocks/large-manual-promo-block/_index.scss
  blocks/large-promo-block/_index.scss
  blocks/medium-manual-promo-block/_index.scss
  blocks/medium-promo-block/_index.scss
  blocks/small-manual-promo-block/_index.scss
  blocks/small-promo-block/_index.scss
Labels: ready for design qa

#1715 Themes 1289 V2 Video Center | Arc block - video needs to resize to handle the correct size when we have vertical video
  blocks/article-body-block/chains/article-body/default.jsx
  blocks/article-body-block/chains/article-body/default.test.jsx
  blocks/lead-art-block/features/leadart/default.jsx
  blocks/lead-art-block/features/leadart/default.test.jsx
  blocks/video-player-block/features/video-player/default.jsx
  blocks/video-player-block/features/video-player/default.test.jsx
Labels: ready for design qa

#1710 THEMES-1206 fix: alert-bar styles
  .storybook/themes/news.scss
  blocks/footer-block/themes/news.json
  blocks/header-nav-chain-block/themes/news.json
Labels: ready for design qa

#1721 Themes 1088
  blocks/gallery-block/features/gallery/default.jsx
  blocks/lead-art-block/features/leadart/default.jsx
Labels: ready to merge
