Repository WPMedia/arc-themes-blocks, pull requests merged in 2023-05, with the labels that each got.

#1638 Themes-725 Remove news-themes-css from v2 blocks repository
  .storybook/main.js
  .storybook/themes/commerce.scss
  .storybook/themes/news.scss
  blocks/article-body-block/themes/commerce.json
  blocks/article-body-block/themes/news.json
  blocks/headline-block/themes/news.json
  blocks/htmlbox-block/features/htmlbox/default.jsx
  blocks/htmlbox-block/styles.scss
  locale/de.json
  locale/en.json
  locale/es.json
  locale/fr.json
  locale/ja.json
  locale/ko.json
  locale/no.json
  locale/pt.json
  locale/sv.json
  package.json
Labels: ready for review

#1650 Update ad size maps for Google update change (flex-cube to right-rail…
  blocks/ads-block/features/ads/ad-mapping.js
  package-lock.json
Labels: ready for review

#1667 added additional validation for author name
  blocks/results-list-block/features/results-list/results/result-item.jsx
Labels: ready for review

#1672 THEMES-1125: Small Promo font weight
  .storybook/themes/news.scss
  blocks/small-promo-block/themes/news.json
Labels: ready to merge

#1668 THEMES-1124 added fonr-weight on heading
  .storybook/themes/news.scss
  blocks/small-manual-promo-block/themes/news.json
Labels: ready to merge

#1571 THEMES-835 Hero block image resizer updates
  blocks/hero-block/features/hero/default.jsx
  blocks/hero-block/features/hero/default.test.jsx
  blocks/hero-block/index.story.jsx
Labels: additional review
