Repository WPMedia/arc-themes-blocks, pull requests merged in 2023-12, with the labels that each got.

#1806 ASUB-7844 PayPal block
  blocks/ads-block/intl.json
  blocks/alert-bar-block/intl.json
  blocks/article-body-block/intl.json
  blocks/author-bio-block/intl.json
  blocks/category-carousel-block/intl.json
  blocks/default-output-block/intl.json
  blocks/footer-block/intl.json
  blocks/full-author-bio-block/intl.json
  blocks/global-phrases-block/intl.json
  blocks/header-nav-chain-block/intl.json
  blocks/identity-block/intl.json
  blocks/lead-art-block/intl.json
  blocks/links-bar-block/intl.json
  blocks/product-assortment-carousel-block/intl.json
  blocks/product-content-block/intl.json
  blocks/product-gallery-block/intl.json
  blocks/product-information-block/intl.json
  blocks/results-list-block/intl.json
  blocks/search-results-list-block/intl.json
  blocks/share-bar-block/intl.json
  blocks/story-carousel-block/intl.json
  blocks/subscriptions-block/_index.scss
  blocks/subscriptions-block/components/PayPal/index.jsx
  blocks/subscriptions-block/components/PayPal/index.test.js
  blocks/subscriptions-block/components/PaymentForm/index.jsx
  blocks/subscriptions-block/components/usePaymentOptions.jsx
  blocks/subscriptions-block/components/usePaymentRedirect.jsx
  blocks/subscriptions-block/features/checkout/_children/PaymentInfo/index.jsx
  blocks/subscriptions-block/features/checkout/default.jsx
  blocks/subscriptions-block/intl.json
  blocks/subscriptions-block/themes/commerce.json
  blocks/subscriptions-block/themes/news.json
  locale/en.json
Labels: ready for review

#1826 THEMES-1218: Logical Properties on Misc Blocks
  .storybook/themes/news.scss
  blocks/alert-bar-block/index.story.jsx
  blocks/alert-bar-block/themes/commerce.json
  blocks/alert-bar-block/themes/news.json
Labels: ready for review, ready to merge

#1827 THEMES-1215: Logical Properties | Footer and Masthead blocks
  .storybook/themes/news.scss
  blocks/footer-block/index.story.mdx
  blocks/footer-block/themes/news.json
  blocks/masthead-block/index.story.jsx
  blocks/masthead-block/themes/news.json
Labels: ready for review, ready to merge

#1829 THEMES-1219: Logical Properties | Lead art and Video player blocks
  .storybook/themes/commerce.scss
  .storybook/themes/news.scss
  blocks/lead-art-block/index.story.jsx
  blocks/lead-art-block/themes/commerce.json
  blocks/lead-art-block/themes/news.json
  blocks/video-player-block/index.story.jsx
  blocks/video-player-block/themes/commerce.json
  blocks/video-player-block/themes/news.json
Labels: ready for review, ready to merge

#1831 ASUB-7844 Fix issue where identity is not defined in paymentInfo
  blocks/subscriptions-block/features/checkout/_children/PaymentInfo/index.jsx
Labels: ready for review

#1828 [THEMES-1374] Implemented logical properties for search-results list and results-list
  .storybook/themes/news.scss
  blocks/results-list-block/index.story.jsx
  blocks/results-list-block/themes/news.json
  blocks/search-results-list-block/index.story.jsx
  blocks/search-results-list-block/themes/news.json
Labels: ready to merge

#1824 Fix paywall Issue
  blocks/subscriptions-block/components/usePaywall.js
Labels: ready for review

#1823 THEMES-1240: Logical properties on header nav chain block
  .storybook/themes/news.scss
  blocks/header-nav-chain-block/index.story.jsx
  blocks/header-nav-chain-block/themes/news.json
Labels: ready to merge

#1813 ASUB-8002 Update payment method
  blocks/identity-block/components/login/index.jsx
  blocks/identity-block/utils/append-url-params.js
  blocks/subscriptions-block/components/PayPal/index.jsx
  blocks/subscriptions-block/components/PaymentForm/index.jsx
  blocks/subscriptions-block/components/usePaymentOptions.jsx
  blocks/subscriptions-block/components/usePaymentRedirect.jsx
  blocks/subscriptions-block/features/checkout/_children/PaymentInfo/index.jsx
  blocks/subscriptions-block/features/checkout/default.jsx
  blocks/subscriptions-block/features/updatePaymentMethod/default.jsx
  blocks/subscriptions-block/intl.json
  locale/en.json
Labels: ready for review

#1833 Update Browserslist
  package.json
Labels: ready for review

#1836 ASUB-7844 Bug fix
  blocks/subscriptions-block/components/usePaywall.js
  blocks/subscriptions-block/features/checkout/_children/PaymentInfo/index.jsx
  blocks/subscriptions-block/features/checkout/default.jsx
Labels: ready for review

#1835 [THEMES-1213] Implemented logical properties on Author blocks
  .storybook/themes/news.scss
  blocks/author-bio-block/index.story.jsx
  blocks/author-bio-block/themes/news.json
  blocks/full-author-bio-block/index.story.jsx
  blocks/full-author-bio-block/themes/news.json
Labels: ready to merge

#1838 Themes 1184
  .storybook/themes/news.scss
  blocks/extra-large-promo-block/index.story.jsx
  blocks/extra-large-promo-block/themes/news.json
  blocks/large-promo-block/index.story.jsx
  blocks/large-promo-block/themes/news.json
  blocks/medium-promo-block/index.story.jsx
  blocks/medium-promo-block/themes/news.json
  blocks/small-promo-block/index.story.jsx
Labels: ready to merge

#1845 Themes 1222 - Logical Properties on Article Body Block
  .storybook/themes/commerce.scss
  .storybook/themes/news.scss
  blocks/article-body-block/index.story.jsx
  blocks/article-body-block/themes/commerce.json
  blocks/article-body-block/themes/news.json
Labels: ready to merge

#1830 [Themes 1212] Added logical properties for numbered-list, card-list, top-table-list and simple-list blocks
  .storybook/themes/news.scss
  blocks/card-list-block/index.story.jsx
  blocks/card-list-block/themes/news.json
  blocks/numbered-list-block/index.story.jsx
  blocks/numbered-list-block/themes/news.json
  blocks/simple-list-block/index.story.jsx
  blocks/top-table-list-block/index.story.jsx
  blocks/top-table-list-block/themes/news.json
Labels: ready to merge

#1844 [THEMES-1214] Implemented logical properties on Share-bar-block
  .storybook/themes/news.scss
  blocks/share-bar-block/index.story.mdx
  blocks/share-bar-block/themes/news.json
Labels: ready to merge

#1848 THEMES-1224 Logical Properties on Ad-Block
  .storybook/themes/news.scss
  blocks/ads-block/index.story.jsx
  blocks/ads-block/themes/commerce.json
  blocks/ads-block/themes/news.json
Labels: ready to merge

#1851 Themes 1578 and 1551- Search Input Behavior
  blocks/header-nav-chain-block/chains/header-nav-chain-block/_children/search-box.jsx
  blocks/header-nav-chain-block/chains/header-nav-chain-block/default.jsx
Labels: ready for review, review in progress

#1846 THEMES-1189: block changes for news theme logical properties
  .eslintrc.js
  .storybook/themes/news.scss
  blocks/gallery-block/index.story.jsx
  blocks/gallery-block/themes/news.json
Labels: ready to merge

#1850 add translations for ar, bn, bo, id, km-kh, lo, ms, my, pt-br, th, ug…
  blocks/ads-block/intl.json
  blocks/alert-bar-block/intl.json
  blocks/article-body-block/intl.json
  blocks/author-bio-block/intl.json
  blocks/category-carousel-block/intl.json
  blocks/default-output-block/intl.json
  blocks/footer-block/intl.json
  blocks/full-author-bio-block/intl.json
  blocks/global-phrases-block/intl.json
  blocks/header-nav-chain-block/intl.json
  blocks/identity-block/intl.json
  blocks/lead-art-block/intl.json
  blocks/links-bar-block/intl.json
  blocks/product-assortment-carousel-block/intl.json
  blocks/product-content-block/intl.json
  blocks/product-gallery-block/intl.json
  blocks/product-information-block/intl.json
  blocks/results-list-block/intl.json
  blocks/search-results-list-block/intl.json
  blocks/share-bar-block/intl.json
  blocks/story-carousel-block/intl.json
  blocks/subscriptions-block/intl.json
  locale/ar.json
  locale/bn.json
  locale/bo.json
  locale/de.json
  locale/en.json
  locale/es.json
  locale/fr.json
  locale/id.json
  locale/ja.json
  locale/km-KH.json
  locale/ko.json
  locale/lo.json
  locale/ms.json
  locale/my.json
  locale/no.json
  locale/pt-BR.json
  locale/pt.json
  locale/sv.json
  locale/th.json
  locale/ug.json
  locale/vi.json
  locale/zh-CN.json
  locale/zh-TW.json
Labels: review in progress

#1842 Updated side-drawer behavior for rtl
  blocks/header-nav-chain-block/themes/news.json
Labels: ready for review

#1856 2.1.2 -> 2.1.3 Merge changes
  blocks/identity-block/components/login/index.jsx
  blocks/identity-block/utils/append-url-params.js
  blocks/subscriptions-block/_index.scss
  blocks/subscriptions-block/components/PayPal/index.jsx
  blocks/subscriptions-block/components/PayPal/index.test.js
  blocks/subscriptions-block/components/PaymentForm/index.jsx
  blocks/subscriptions-block/components/usePaymentOptions.jsx
  blocks/subscriptions-block/components/usePaymentRedirect.jsx
  blocks/subscriptions-block/components/usePaywall.js
  blocks/subscriptions-block/features/checkout/_children/PaymentInfo/index.jsx
  blocks/subscriptions-block/features/checkout/default.jsx
  blocks/subscriptions-block/features/updatePaymentMethod/default.jsx
  blocks/subscriptions-block/themes/commerce.json
  blocks/subscriptions-block/themes/news.json
  package-lock.json
Labels: ready for review

#1854 THEMES-1580 added transform to related-content
  blocks/related-content-content-source-block/sources/related-content.js
Labels: ready for review
