Repository WPMedia/arc-themes-blocks, pull requests merged in 2023-02, with the labels that each got.

#1608 THEMES-995: ChartBeat field names
  blocks/default-output-block/output-types/__tests__/default.test.jsx
  blocks/default-output-block/output-types/default.jsx
Labels: ready to merge

#1612 THEMES-995: ChartBeat field names - 1.25
  blocks/default-output-block/output-types/__tests__/default.test.jsx
  blocks/default-output-block/output-types/default.jsx
Labels: ready for review

#1615 Update signing service call to use new v2 contract
  blocks/signing-service-content-source-block/sources/signing-service.js
  blocks/signing-service-content-source-block/sources/signing-service.test.js
Labels: ready for review

#1616 removed icon label in mobile
  .storybook/themes/news.scss
Labels: ready for design qa

#1607 Themes 685 Implemented Video icon and label
  .storybook/mock-content/extraLargePromo.js
  .storybook/themes/news.scss
  blocks/extra-large-promo-block/_index.scss
  blocks/extra-large-promo-block/features/extra-large-promo/default.jsx
  blocks/extra-large-promo-block/features/extra-large-promo/default.test.jsx
  blocks/extra-large-promo-block/index.story.jsx
Labels: ready to merge, ready for design qa

#1620 THEMES-996: Add blocks to commerce
  .storybook/themes/commerce.scss
Labels: ready for review

#1619 THEMES-965: Add themes=v2 parameter to each used content source
  blocks/alert-bar-content-source-block/sources/alert-bar-collections.js
  blocks/alert-bar-content-source-block/sources/alert-bar-collections.test.js
  blocks/author-content-source-block/sources/author-api.js
  blocks/author-content-source-block/sources/author-api.test.js
  blocks/collections-content-source-block/sources/content-api-collections.js
  blocks/collections-content-source-block/sources/content-api-collections.test.js
  blocks/content-api-source-block/sources/content-api.js
  blocks/content-api-source-block/sources/content-api.test.js
  blocks/related-content-content-source-block/sources/related-content.js
  blocks/related-content-content-source-block/sources/related-content.test.js
  blocks/search-content-source-block/sources/search-api.js
  blocks/search-content-source-block/sources/search-api.test.js
  blocks/story-feed-author-content-source-block/sources/story-feed-author.js
  blocks/story-feed-author-content-source-block/sources/story-feed-author.test.jsx
  blocks/story-feed-query-content-source-block/sources/story-feed-query.js
  blocks/story-feed-query-content-source-block/sources/story-feed-query.test.js
  blocks/story-feed-sections-content-source-block/sources/story-feed-sections.js
  blocks/story-feed-sections-content-source-block/sources/story-feed-sections.test.js
  blocks/story-feed-tag-content-source-block/sources/story-feed-tag.js
  blocks/story-feed-tag-content-source-block/sources/story-feed-tag.test.js
  blocks/tags-content-source-block/sources/tags-api.js
  blocks/tags-content-source-block/sources/tags-api.test.js
  blocks/unpublished-content-source-block/sources/content-api-unpublished.js
  blocks/unpublished-content-source-block/sources/content-api-unpublished.test.js
Labels: ready to merge

#1625 Update package.json for the new release
  package-lock.json
  package.json
Labels: ready for review

#1627 Removing SASS division values and replacing with css calc()
  .storybook/themes/commerce.scss
  .storybook/themes/news.scss
Labels: ready for review

#1622 Updated right-rail layout for THEMES-923
  blocks/right-rail-block/layouts/right-rail/default.jsx
Labels: ready to merge

#1626 THEMES-1024: Add catch for Axios calls
  blocks/collections-content-source-block/sources/content-api-collections.js
  blocks/collections-content-source-block/sources/content-api-collections.test.js
Labels: ready for review

#1628 THEMES-965: Add themes param to content sources
  blocks/alert-bar-content-source-block/sources/alert-bar-collections.js
  blocks/alert-bar-content-source-block/sources/alert-bar-collections.test.js
  blocks/author-content-source-block/sources/author-api.js
  blocks/author-content-source-block/sources/author-api.test.js
  blocks/collections-content-source-block/sources/content-api-collections.js
  blocks/collections-content-source-block/sources/content-api-collections.test.js
  blocks/content-api-source-block/sources/content-api.js
  blocks/content-api-source-block/sources/content-api.test.js
  blocks/related-content-content-source-block/sources/related-content.js
  blocks/related-content-content-source-block/sources/related-content.test.js
  blocks/search-content-source-block/sources/search-api.js
  blocks/search-content-source-block/sources/search-api.test.js
  blocks/story-feed-author-content-source-block/sources/story-feed-author.js
  blocks/story-feed-author-content-source-block/sources/story-feed-author.test.jsx
  blocks/story-feed-query-content-source-block/sources/story-feed-query.js
  blocks/story-feed-query-content-source-block/sources/story-feed-query.test.js
  blocks/story-feed-sections-content-source-block/sources/story-feed-sections.js
  blocks/story-feed-sections-content-source-block/sources/story-feed-sections.test.js
  blocks/story-feed-tag-content-source-block/sources/story-feed-tag.js
  blocks/story-feed-tag-content-source-block/sources/story-feed-tag.test.js
  blocks/tags-content-source-block/sources/tags-api.js
  blocks/tags-content-source-block/sources/tags-api.test.js
  blocks/unpublished-content-source-block/sources/content-api-unpublished.js
  blocks/unpublished-content-source-block/sources/content-api-unpublished.test.js
Labels: ready for review, ready to merge
