Repository WPMedia/arc-themes-blocks, pull requests merged in 2023-07, with the labels that each got.

#1682 Themes 1191 alert bar hover styles
  .storybook/themes/commerce.scss
  .storybook/themes/news.scss
  blocks/alert-bar-block/themes/commerce.json
  blocks/alert-bar-block/themes/news.json
Labels: ready to merge

#1689 THEMES 1199 byline hover styles
  .storybook/themes/news.scss
  blocks/byline-block/themes/news.json
Labels: ready to merge

#1694 THEMES-1173: header nav | Update button component to match new design
  .storybook/themes/news.scss
  blocks/header-nav-chain-block/_index.scss
  blocks/header-nav-chain-block/themes/news.json
Labels: ready to merge

#1696 Fix for THEMES-961 broken message on initial load
  blocks/search-results-list-block/features/search-results-list/_children/search-field.jsx
Labels: ready to merge, small-improvement

#1695 THEMES-757: Identity Blocks | Header action block
  blocks/identity-block/CHANGELOG.md
  blocks/identity-block/README.md
  blocks/identity-block/_index.scss
  blocks/identity-block/components/.npmignore
  blocks/identity-block/components/Identity.jsx
  blocks/identity-block/components/Identity.test.jsx
  blocks/identity-block/features/.npmignore
  blocks/identity-block/features/header-account-action/_children/DropDownLinkListItem.jsx
  blocks/identity-block/features/header-account-action/_children/DropdownLinkListItem.test.jsx
  blocks/identity-block/features/header-account-action/default.jsx
  blocks/identity-block/features/header-account-action/default.test.jsx
  blocks/identity-block/features/header-account-action/index.story-ignore.jsx
  blocks/identity-block/intl.json
  blocks/identity-block/jest.config.js
  blocks/identity-block/package-lock.json
  blocks/identity-block/package.json
  blocks/identity-block/themes/commerce.json
  blocks/identity-block/themes/news.json
Labels: review in progress

#1698 Added dir attribute to html tag
  blocks/default-output-block/output-types/__tests__/default.test.jsx
  blocks/default-output-block/output-types/default.jsx
Labels: ready to merge

#1699 THEMES-1206 - fix: footer margin
  blocks/footer-block/themes/news.json
Labels: ready for review

#1703 Added writing mode style tag to page head
  blocks/default-output-block/output-types/__tests__/default.test.jsx
  blocks/default-output-block/output-types/default.jsx
Labels: ready to merge

#1701 Themes 1199.5 byline hover redux
  .storybook/themes/news.scss
  blocks/byline-block/themes/news.json
Labels: ready to merge, small-improvement

#1706 Revert "Rest state styling support added"
  blocks/author-bio-block/_index.scss
  blocks/author-bio-block/themes/news.json
Labels: ready for review

#1705 THEMES-758: Identity Block | Sign Up Block
  blocks/identity-block/_index.scss
  blocks/identity-block/components/FormPasswordConfirm/index.jsx
  blocks/identity-block/components/FormPasswordConfirm/index.story-ignore.jsx
  blocks/identity-block/components/FormPasswordConfirm/index.test.jsx
  blocks/identity-block/components/HeadlinedSubmitForm/index.jsx
  blocks/identity-block/components/HeadlinedSubmitForm/index.story-ignore.jsx
  blocks/identity-block/components/HeadlinedSubmitForm/index.test.jsx
  blocks/identity-block/components/Identity.test.jsx
  blocks/identity-block/features/signup/default.jsx
  blocks/identity-block/features/signup/default.test.jsx
  blocks/identity-block/intl.json
  blocks/identity-block/themes/commerce.json
  blocks/identity-block/themes/news.json
  blocks/identity-block/utils/password-validation-message.js
  blocks/identity-block/utils/password-validation-message.test.js
  blocks/identity-block/utils/validate-password-pattern.js
  blocks/identity-block/utils/validate-password-pattern.test.js
  locale/de.json
  locale/en.json
  locale/es.json
  locale/fr.json
  locale/ja.json
  locale/ko.json
  locale/no.json
  locale/pt.json
  locale/sv.json
Labels: ready for review, review in progress

#1709 THEMES 1187 Header Nav Chain Block - React code update to support RTL
  .storybook/themes/news.scss
  blocks/header-nav-chain-block/_index.scss
  blocks/header-nav-chain-block/chains/header-nav-chain-block/_children/nav-links/default.jsx
  blocks/header-nav-chain-block/chains/header-nav-chain-block/_children/nav-logo.jsx
  blocks/header-nav-chain-block/chains/header-nav-chain-block/default.jsx
  blocks/header-nav-chain-block/themes/news.json
Labels: ready to merge

#1693 fix: exception in links-bar-block
  blocks/links-bar-block/features/links-bar/default.jsx
  blocks/links-bar-block/features/links-bar/default.test.jsx
Labels: ready to merge

#1690 THEMES-1195 Updated headline, overline and image opacity
  .storybook/mock-content/extraLargePromo.js
  .storybook/mock-content/largePromo.js
  .storybook/mock-content/mediumPromo.js
  .storybook/mock-content/smallPromo.js
  .storybook/themes/news.scss
  blocks/extra-large-manual-promo-block/_index.scss
  blocks/extra-large-manual-promo-block/features/extra-large-manual-promo/default.jsx
  blocks/extra-large-manual-promo-block/themes/news.json
  blocks/extra-large-promo-block/_index.scss
  blocks/extra-large-promo-block/features/extra-large-promo/default.jsx
  blocks/extra-large-promo-block/themes/news.json
  blocks/large-manual-promo-block/_index.scss
  blocks/large-manual-promo-block/features/large-manual-promo/default.jsx
  blocks/large-manual-promo-block/themes/news.json
  blocks/large-promo-block/_index.scss
  blocks/large-promo-block/features/large-promo/default.jsx
  blocks/large-promo-block/themes/news.json
  blocks/medium-manual-promo-block/_index.scss
  blocks/medium-manual-promo-block/features/medium-manual-promo/default.jsx
  blocks/medium-manual-promo-block/themes/news.json
  blocks/medium-promo-block/_index.scss
  blocks/medium-promo-block/features/medium-promo/default.jsx
  blocks/medium-promo-block/themes/news.json
  blocks/small-manual-promo-block/_index.scss
  blocks/small-manual-promo-block/features/small-manual-promo/default.jsx
  blocks/small-manual-promo-block/themes/news.json
  blocks/small-promo-block/_index.scss
  blocks/small-promo-block/features/small-promo/default.jsx
  blocks/small-promo-block/themes/news.json
Labels: ready for design qa

#1711 THEMES-759: Identity Blocks | Log in form
  blocks/identity-block/_index.scss
  blocks/identity-block/components/form-password-confirm/index.jsx
  blocks/identity-block/components/form-password-confirm/index.story-ignore.jsx
  blocks/identity-block/components/form-password-confirm/index.test.jsx
  blocks/identity-block/components/headlined-submit-form/index.jsx
  blocks/identity-block/components/headlined-submit-form/index.story-ignore.jsx
  blocks/identity-block/components/headlined-submit-form/index.test.jsx
  blocks/identity-block/components/identity/index.jsx
  blocks/identity-block/components/identity/index.test.jsx
  blocks/identity-block/components/login/index.jsx
  blocks/identity-block/components/login/index.test.jsx
  blocks/identity-block/features/header-account-action/default.jsx
  blocks/identity-block/features/header-account-action/default.test.jsx
  blocks/identity-block/features/login/default.jsx
  blocks/identity-block/features/login/default.test.jsx
  blocks/identity-block/features/signup/default.jsx
  blocks/identity-block/features/signup/default.test.jsx
  blocks/identity-block/themes/commerce.json
  blocks/identity-block/themes/news.json
Labels: ready for review
