Repository WPMedia/arc-themes-blocks, pull requests merged in 2023-01, with the labels that each got.

#1583 Add missing dependencies object in package.json
  blocks/alert-bar-content-source-block/package.json
  blocks/author-content-source-block/package.json
  blocks/site-hierarchy-content-block/package.json
  blocks/story-feed-author-content-source-block/package.json
  blocks/story-feed-query-content-source-block/package.json
  blocks/story-feed-sections-content-source-block/package.json
  blocks/story-feed-tag-content-source-block/package.json
  blocks/tags-content-source-block/package.json
Labels: ready for review

#1586 THEMES-837: Category Carousel Block resizer update
  blocks/category-carousel-block/_index.scss
  blocks/category-carousel-block/features/category-carousel/default.jsx
  blocks/category-carousel-block/features/category-carousel/default.test.jsx
  blocks/category-carousel-block/index.story.jsx
Labels: ready for design qa

#1591 Use nvmrc to control node version in use
  .github/workflows/arc-themes-base-to-new-tag.yml
  .github/workflows/chromatic.yml
  .github/workflows/generate-intl-files.yml
  .github/workflows/stylelint-pr.yml
  .github/workflows/sync-themes-branch-with-themes-tag.yml
  .github/workflows/test-coverage-blocks.yml
  .nvmrc
Labels: ready to merge

#1594 THEMES-897 - Update default dateTimeFormat string to match new requirement
  .storybook/alias/properties.js
  blocks/date-block/features/date/default.jsx
  blocks/date-block/features/date/default.test.jsx
  blocks/extra-large-promo-block/features/extra-large-promo/default.jsx
  blocks/large-promo-block/features/large-promo/default.jsx
  blocks/large-promo-block/features/large-promo/default.test.jsx
  blocks/medium-promo-block/features/medium-promo/default.jsx
  blocks/top-table-list-block/features/top-table-list/_children/extra-large.jsx
  blocks/top-table-list-block/features/top-table-list/_children/large.jsx
  blocks/top-table-list-block/features/top-table-list/_children/medium.jsx
  package-lock.json
Labels: ready for review

#1595 URLSearchParams should not have encoded values passed to it
  blocks/search-content-source-block/sources/search-api.js
  blocks/search-content-source-block/sources/search-api.test.js
Labels: ready to merge

#1588 Added close button on image stories
  .storybook/themes/news.scss
  blocks/lead-art-block/_index.scss
  blocks/lead-art-block/features/leadart/default.jsx
Labels: ready for design qa

#1598 Fixed imageRatio issue
  blocks/results-list-block/features/results-list/default.jsx
Labels: ready for review

#1600 THEMES-747: Create token blocks
  blocks/alias-tokens/CHANGELOG.md
  blocks/alias-tokens/README.md
  blocks/alias-tokens/package-lock.json
  blocks/alias-tokens/package.json
  blocks/alias-tokens/themes/commerce.json
  blocks/alias-tokens/themes/news.json
  blocks/breakpoint-tokens/CHANGELOG.md
  blocks/breakpoint-tokens/README.md
  blocks/breakpoint-tokens/package-lock.json
  blocks/breakpoint-tokens/package.json
  blocks/breakpoint-tokens/themes/commerce.json
  blocks/breakpoint-tokens/themes/news.json
  blocks/global-tokens/README.md
  blocks/global-tokens/package-lock.json
  blocks/global-tokens/package.json
  blocks/global-tokens/themes/commerce.json
  blocks/global-tokens/themes/news.json
  package-lock.json
Labels: ready to merge

#1602 Fixed localize for links
  blocks/full-author-bio-block/features/full-author-bio/_children/Presentation/index.jsx
Labels: ready to merge

#1601 Themes 919 image height fix
  blocks/results-list-block/features/results-list/default.jsx
  blocks/results-list-block/features/results-list/results/result-item.jsx
  blocks/results-list-block/features/results-list/results/result-item.test.jsx
  blocks/results-list-block/index.story.jsx
Labels: ready to merge
