Repository WPMedia/arc-themes-blocks, pull requests merged in 2024-06, with the labels that each got.

#2148 THEMES-1916: Update Author images to use signed resizer images if available.
  blocks/author-bio-block/features/author-bio/default.jsx
  blocks/author-bio-block/features/author-bio/default.test.jsx
  blocks/full-author-bio-block/features/full-author-bio/_children/Presentation/index.jsx
  blocks/full-author-bio-block/features/full-author-bio/_children/Presentation/index.test.jsx
  blocks/full-author-bio-block/features/full-author-bio/default.test.jsx
  blocks/full-author-bio-block/package-lock.json
Labels: ready for review, review in progress

#2152 updated cardlist block to respect offsetOverride
  blocks/card-list-block/features/card-list/default.jsx
  blocks/card-list-block/features/card-list/default.test.jsx
Labels: ready to merge

#2162 THEMES-1906: Use correct info when calling signing service
  blocks/extra-large-manual-promo-block/features/extra-large-manual-promo/default.jsx
  blocks/extra-large-promo-block/features/extra-large-promo/default.jsx
  blocks/hero-block/features/hero/default.jsx
  blocks/large-manual-promo-block/features/large-manual-promo/default.jsx
  blocks/large-promo-block/features/large-promo/default.jsx
  blocks/medium-manual-promo-block/features/medium-manual-promo/default.jsx
  blocks/medium-promo-block/features/medium-promo/default.jsx
  blocks/results-list-block/features/results-list/results/result-item.jsx
  blocks/small-manual-promo-block/features/small-manual-promo/default.jsx
  blocks/small-promo-block/features/small-promo/default.jsx
  package-lock.json
Labels: ready for review

#2163 THEMES-1916: Full Author was not accounting for "original" author data
  blocks/full-author-bio-block/features/full-author-bio/_children/Presentation/index.jsx
  blocks/full-author-bio-block/features/full-author-bio/_children/Presentation/index.test.jsx
  blocks/full-author-bio-block/features/full-author-bio/default.jsx
  blocks/full-author-bio-block/index.story.jsx
  package-lock.json
Labels: ready to merge

#2138 Bug/asub 8456 reset password login redirect issue
  .eslintrc.js
  blocks/identity-block/components/login/index.jsx
  blocks/identity-block/components/login/index.test.jsx
  blocks/identity-block/components/social-sign-on/utils/useSocialSignIn.js
  blocks/identity-block/features/login/default.jsx
  blocks/identity-block/features/one-time-password/default.test.jsx
  blocks/identity-block/features/reset-password/default.jsx
  blocks/identity-block/features/reset-password/default.test.jsx
  blocks/identity-block/utils/validate-redirect-url.js
  blocks/identity-block/utils/validate-redirect-url.test.js
Labels: ready to merge
