Repository WPMedia/arc-themes-blocks, pull requests merged in 2024-05, with the labels that each got.

#2107 Asub 8384/subs profile
  blocks/subscriptions-block/_index.scss
  blocks/subscriptions-block/components/PriceRates/index.jsx
  blocks/subscriptions-block/components/PriceRates/index.test.jsx
  blocks/subscriptions-block/components/usePrice.jsx
  blocks/subscriptions-block/components/utils.js
  blocks/subscriptions-block/components/utils.test.js
  blocks/subscriptions-block/features/SubscriptionProfileManagement/children/BasicSubscriptionDetail/index.jsx
  blocks/subscriptions-block/features/SubscriptionProfileManagement/children/BasicSubscriptionDetail/index.test.jsx
  blocks/subscriptions-block/features/SubscriptionProfileManagement/children/BillingAddressDetails/index.jsx
  blocks/subscriptions-block/features/SubscriptionProfileManagement/children/BillingAddressDetails/index.test.jsx
  blocks/subscriptions-block/features/SubscriptionProfileManagement/children/PaymentMethodDetails/index.jsx
  blocks/subscriptions-block/features/SubscriptionProfileManagement/children/PaymentMethodDetails/index.test.jsx
  blocks/subscriptions-block/features/SubscriptionProfileManagement/children/SubscriptionCard/index.jsx
  blocks/subscriptions-block/features/SubscriptionProfileManagement/children/SubscriptionCard/index.test.jsx
  blocks/subscriptions-block/features/SubscriptionProfileManagement/children/SubscriptionProfileManagementList/index.jsx
  blocks/subscriptions-block/features/SubscriptionProfileManagement/children/SubscriptionProfileManagementList/index.test.jsx
  blocks/subscriptions-block/features/SubscriptionProfileManagement/default.jsx
  blocks/subscriptions-block/features/SubscriptionProfileManagement/default.test.jsx
  blocks/subscriptions-block/intl.json
  blocks/subscriptions-block/themes/news.json
  locale/en.json
Labels: ready to merge

#2110 Asub 8194/magic link login without pw
  .storybook/themes/news.scss
  blocks/identity-block/_index.scss
  blocks/identity-block/components/headlined-submit-form/index.jsx
  blocks/identity-block/features/login-links/default.jsx
  blocks/identity-block/features/login-links/default.test.jsx
  blocks/identity-block/features/one-time-password/default.jsx
  blocks/identity-block/features/one-time-password/default.test.jsx
  blocks/identity-block/intl.json
  blocks/identity-block/themes/news.json
  locale/en.json
  package-lock.json
  package.json
Labels: ready for review

#2132 [Themes 1930] Added height to header-nav-chain-flyout-overlay-open
  .storybook/themes/news.scss
  blocks/header-nav-chain-block/themes/news.json
Labels: ready for review

#2141 [Themes 1676] Fixed triple-chain large-manual-promo Desktop view
  .storybook/themes/news.scss
  blocks/triple-chain-block/_index.scss
  blocks/triple-chain-block/themes/news.json
Labels: ready to merge

#2130 [THEMES-968] Updated Article body block test cases to react-testing-library
  blocks/article-body-block/chains/article-body/_children/heading.test.jsx
  blocks/article-body-block/chains/article-body/_children/html.test.jsx
  blocks/article-body-block/chains/article-body/_children/list.test.jsx
  blocks/article-body-block/chains/article-body/_children/oembed.jsx
  blocks/article-body-block/chains/article-body/_children/oembed.test.jsx
  blocks/article-body-block/chains/article-body/_children/quote.jsx
  blocks/article-body-block/chains/article-body/_children/quote.test.jsx
  blocks/article-body-block/chains/article-body/_children/table.test.jsx
  blocks/article-body-block/chains/article-body/default.jsx
  blocks/article-body-block/chains/article-body/default.test.jsx
Labels: ready for review

#2142 added configurations for collections search
  blocks/collections-content-source-block/sources/content-api-collections.js
Labels: ready to merge

#1975 [THEMES-1744] Converted article-tag-block test suits to react testing library
  blocks/article-tag-block/features/tag/default.jsx
  blocks/article-tag-block/features/tag/default.test.jsx
Labels: ready to merge

#2143 [Themes 1884 ] fix
  blocks/top-table-list-block/features/top-table-list/_children/extra-large.jsx
  blocks/top-table-list-block/features/top-table-list/_children/extra-large.test.jsx
  package-lock.json
  package.json
Labels: ready to merge

#2135 THEMES-1666/THEMES-1898: Accessible nav menu button and Greek language support
  .storybook/themes/news.scss
  blocks/ads-block/intl.json
  blocks/alert-bar-block/intl.json
  blocks/article-body-block/intl.json
  blocks/author-bio-block/intl.json
  blocks/category-carousel-block/intl.json
  blocks/default-output-block/intl.json
  blocks/footer-block/intl.json
  blocks/full-author-bio-block/intl.json
  blocks/global-phrases-block/intl.json
  blocks/header-nav-chain-block/_index.scss
  blocks/header-nav-chain-block/chains/header-nav-chain-block/default.jsx
  blocks/header-nav-chain-block/chains/header-nav-chain-block/default.test.jsx
  blocks/header-nav-chain-block/index.story.jsx
  blocks/header-nav-chain-block/intl.json
  blocks/header-nav-chain-block/themes/news.json
  blocks/identity-block/intl.json
  blocks/lead-art-block/intl.json
  blocks/links-bar-block/intl.json
  blocks/product-assortment-carousel-block/intl.json
  blocks/product-content-block/intl.json
  blocks/product-gallery-block/features/product-gallery/_children/ProductFocusView/index.jsx
  blocks/product-gallery-block/intl.json
  blocks/product-information-block/intl.json
  blocks/results-list-block/intl.json
  blocks/search-results-list-block/intl.json
  blocks/share-bar-block/intl.json
  blocks/story-carousel-block/intl.json
  blocks/subscriptions-block/intl.json
  locale/ar.json
  locale/bn.json
  locale/bo.json
  locale/de.json
  locale/el.json
  locale/en.json
  locale/es.json
  locale/fr.json
  locale/id.json
  locale/ja.json
  locale/km-KH.json
  locale/ko.json
  locale/lo.json
  locale/ms.json
  locale/my.json
  locale/no.json
  locale/pt-BR.json
  locale/pt.json
  locale/sv.json
  locale/th.json
  locale/ug.json
  locale/vi.json
  locale/zh-CN.json
  locale/zh-TW.json
Labels: ready for review

#2088 [Themes-1688] Fixed inconsistent image width
  .storybook/themes/news.scss
  blocks/top-table-list-block/themes/news.json
Labels: additional review

#2133 ASUB-8484 Including threshold for pending order and fixing styles
  blocks/subscriptions-block/_index.scss
  blocks/subscriptions-block/components/useCartOrderDetail.jsx
  blocks/subscriptions-block/components/useCartOrderDetail.test.jsx
  blocks/subscriptions-block/features/checkout/_children/BillingAddress/index.jsx
  blocks/subscriptions-block/features/checkout/_children/BillingAddress/index.test.jsx
  blocks/subscriptions-block/features/checkout/_children/PaymentReview/index.jsx
  blocks/subscriptions-block/features/checkout/default.jsx
  blocks/subscriptions-block/features/checkout/default.test.jsx
  blocks/subscriptions-block/themes/news.json
Labels: ready to merge

#2129 ASUB-8476 Redeem ota link
  blocks/identity-block/_index.scss
  blocks/identity-block/features/one-time-password/default.jsx
  blocks/identity-block/features/one-time-password/default.test.jsx
  blocks/identity-block/intl.json
  blocks/identity-block/themes/news.json
  blocks/subscriptions-block/intl.json
  locale/ar.json
  locale/bn.json
  locale/bo.json
  locale/de.json
  locale/el.json
  locale/en.json
  locale/es.json
  locale/fr.json
  locale/id.json
  locale/ja.json
  locale/km-KH.json
  locale/ko.json
  locale/lo.json
  locale/ms.json
  locale/my.json
  locale/no.json
  locale/pt-BR.json
  locale/pt.json
  locale/sv.json
  locale/th.json
  locale/ug.json
  locale/vi.json
  locale/zh-CN.json
  locale/zh-TW.json
Labels: ready to merge

#2151 [Themes 1688] regression error fix
  .storybook/themes/news.scss
  blocks/top-table-list-block/features/top-table-list/_children/medium.jsx
  blocks/top-table-list-block/themes/news.json
Labels: review in progress
