Repository WPMedia/arc-themes-blocks, pull requests merged in 2024-04, with the labels that each got.

#1996 Manual promo blocks now respect focal point
  blocks/extra-large-manual-promo-block/features/extra-large-manual-promo/default.jsx
  blocks/extra-large-manual-promo-block/features/extra-large-manual-promo/default.test.jsx
  blocks/large-manual-promo-block/features/large-manual-promo/default.jsx
  blocks/large-manual-promo-block/features/large-manual-promo/default.test.jsx
  blocks/medium-manual-promo-block/features/medium-manual-promo/default.jsx
  blocks/medium-manual-promo-block/features/medium-manual-promo/default.test.jsx
  blocks/small-manual-promo-block/features/small-manual-promo/default.jsx
  blocks/small-manual-promo-block/features/small-manual-promo/default.test.jsx
  package.json
Labels: ready to merge

#2067 ASUB-8201 Sign In with Apple
  blocks/identity-block/_index.scss
  blocks/identity-block/components/login/index.jsx
  blocks/identity-block/components/social-sign-on/_children/AppleSignIn.jsx
  blocks/identity-block/components/social-sign-on/_children/AppleSignIn.test.jsx
  blocks/identity-block/components/social-sign-on/_children/FacebookSignIn.jsx
  blocks/identity-block/components/social-sign-on/constants.js
  blocks/identity-block/components/social-sign-on/index.jsx
  blocks/identity-block/components/social-sign-on/utils/useSocialSignIn.js
  blocks/identity-block/features/account-management/_children/EmailEditableFieldContainer.test.jsx
  blocks/identity-block/features/account-management/_children/PasswordEditableFieldContainer.test.jsx
  blocks/identity-block/features/account-management/default.jsx
  blocks/identity-block/features/account-management/default.test.jsx
  blocks/identity-block/features/login-links/default.jsx
  blocks/identity-block/features/login/default.jsx
  blocks/identity-block/features/signup/default.jsx
  blocks/identity-block/features/social-sign-on/default.jsx
  blocks/identity-block/features/social-sign-on/default.test.jsx
  blocks/identity-block/intl.json
  blocks/identity-block/themes/news.json
  locale/en.json
  package-lock.json
Labels: ready to merge

#2068 ASUB-8195 Sign up with reCaptcha
  blocks/identity-block/_index.scss
  blocks/identity-block/components/bot-challenge-protection/index.jsx
  blocks/identity-block/components/bot-challenge-protection/index.test.jsx
  blocks/identity-block/components/bot-challenge-protection/reCaptchaV3.js
  blocks/identity-block/components/form-password-confirm/index.jsx
  blocks/identity-block/components/form-password-confirm/index.test.jsx
  blocks/identity-block/features/login/default.jsx
  blocks/identity-block/features/login/default.test.jsx
  blocks/identity-block/features/signup/default.jsx
  blocks/identity-block/features/signup/default.test.jsx
  blocks/identity-block/intl.json
  blocks/identity-block/themes/news.json
  blocks/identity-block/utils/useRecaptcha.js
  blocks/identity-block/utils/useRecaptcha.test.js
  locale/en.json
  package-lock.json
Labels: ready to merge

#2092 Lokalize-translation 2.3.0
  blocks/identity-block/intl.json
  blocks/subscriptions-block/intl.json
  locale/ar.json
  locale/bn.json
  locale/bo.json
  locale/de.json
  locale/es.json
  locale/fr.json
  locale/id.json
  locale/ja.json
  locale/km-KH.json
  locale/ko.json
  locale/lo.json
  locale/ms.json
  locale/my.json
  locale/no.json
  locale/pt-BR.json
  locale/pt.json
  locale/sv.json
  locale/th.json
  locale/ug.json
  locale/vi.json
  locale/zh-CN.json
  locale/zh-TW.json
Labels: ready to merge

#2090 THEMES-1066: Update Storybook to v8
  .github/workflows/chromatic.yml
  .github/workflows/stylelint-pr.yml
  .storybook/.babelrc
  .storybook/main.js
  .storybook/manager.js
  .storybook/preview.js
  .storybook/themes/news.scss
  .stylelintrc.json
  babel.config.js
  blocks/ads-block/index.story.jsx
  blocks/alert-bar-block/index.story.jsx
  blocks/article-tag-block/index.story.jsx
  blocks/author-bio-block/index.story.jsx
  blocks/byline-block/index.story.jsx
  blocks/byline-block/index.story.mdx
  blocks/card-list-block/index.story.jsx
  blocks/double-chain-block/index.story.jsx
  blocks/footer-block/index.story.jsx
  blocks/footer-block/index.story.mdx
  blocks/full-author-bio-block/index.story.jsx
  blocks/gallery-block/index.story.jsx
  blocks/headline-block/index.story.jsx
  blocks/identity-block/_index.scss
  blocks/large-manual-promo-block/index.story.jsx
  blocks/links-bar-block/index.story.jsx
  blocks/masthead-block/index.story.jsx
  blocks/medium-manual-promo-block/index.story.jsx
  blocks/medium-promo-block/index.story.jsx
  blocks/numbered-list-block/index.story.jsx
  blocks/overline-block/index.story.jsx
  blocks/overline-block/index.story.mdx
  blocks/product-featured-image-block/index.story.jsx
  blocks/quad-chain-block/index.story.jsx
  blocks/results-list-block/index.story.jsx
  blocks/right-rail-advanced-block/index.story.jsx
  blocks/right-rail-block/index.story.jsx
  blocks/search-results-list-block/index.story.jsx
  blocks/section-title-block/index.story.jsx
  blocks/share-bar-block/index.story.jsx
  blocks/share-bar-block/index.story.mdx
  blocks/simple-list-block/index.story.jsx
  blocks/single-chain-block/index.story.jsx
  blocks/single-column-layout-block/index.story.jsx
  blocks/small-manual-promo-block/index.story.jsx
  blocks/small-promo-block/index.story.jsx
  blocks/tag-title-block/index.story.jsx
  blocks/triple-chain-block/index.story.jsx
  package-lock.json
  package.json
  stories/aaaIntro.mdx
Labels: ready for review

#2056 Upgraded release-version to 2.3.1
  package-lock.json
  package.json
Labels: do not merge

#2106 THEMES-1900: Fix logic for detecting 404 for sectionId/_id
  .editorconfig
  blocks/site-hierarchy-content-block/sources/site-service-hierarchy.js
Labels: ready for review
